### ISSUE TITLE
Puppet cannot create a plan when PuppetRole is re-created

### ISSUE THREAD

**Issue by jordan-evans** [awslabs/aws-service-catalog-puppet#105]
In a spoke account, if the PuppetRole has been deleted & re-created, Puppet cannot execute a product plan as the new PuppetRole is no longer the owner of the provisioned product.

**Comment by eamonnfaherty** [comment]
This is work in progress.

Expected to release tomorrow.

**Comment by eamonnfaherty** [comment]
Just to clarify for others:

If you create a role named PuppetRole.  Use that role to provision a product and then delete that role you can no longer update that provisioned product.  This is how AWS Service Catalog works and is not specific to this tool.

**Comment by eamonnfaherty** [comment]
fixed
