### ISSUE TITLE
Parallel Deployment of a Launch

### ISSUE THREAD

**Issue by jordan-evans** [awslabs/aws-service-catalog-puppet#107]
At the moment it looks like for a given launch, Puppet carries out a sequential deployment against each applicable account. I.e. for a launch, it deploys to Account 1, then deploys to Account 2 etc).

It would be good if a given launch was deployed across all applicable accounts in parallel.

I've just created 2 new AWS accounts ad run the Puppet Pipeline, and can see this behaviour.

**Comment by eamonnfaherty** [comment]
The following code is the issue.  It is limiting the scheduling of tasks to workers such that only one region is run at a time across any number of accounts.

```
    @property
    def resources(self):
        resources_for_this_task = {}

        if hasattr(self, 'region'):
            resources_for_this_task[self.region] = 1

        return resources_for_this_task
```

Will release a fix for this tomorrow.

**Comment by eamonnfaherty** [comment]
I have just pushed this release.  Please bear in mind there is still the limit of how many worker are enabled.  At the moment it is hard coded to 10.  This should mean you see 10 provisions occur at the same time.  If you need more (or less) please raise a ticket.
