### ISSUE TITLE
Tags missing from local portfolios & products

### ISSUE THREAD

**Issue by jordan-evans** [awslabs/aws-service-catalog-puppet#110]
When a portfolio & product is copied to a spoke account, the tags are not persisted. By the looks of it it doesn't look like the imported portfolios / products preserve tags either.

It would also be useful if new tags were added, and old tags removed, if the parent portfolio / product tags were updated

**Comment by eamonnfaherty** [comment]
CopyTags was added to the copy_products command in release 0.14.0
