### ISSUE TITLE
spoke-local-portfolios products should respect deactivated versions in parent portfolio

### ISSUE THREAD

**Issue by jordan-evans** [awslabs/aws-service-catalog-puppet#124]
At the moment if we share a portfolio to a spoke account via `spoke-local-portfolios`, and then deactivate a product version in the parent portfolio, that version remains active in the local spoke portfolio.

It would be good if Puppet deactivated / activated product versions in spoke portfolios, based on their activation status in the parent portfolio.

**Comment by eamonnfaherty** [comment]
Hi @jordan-evans 

I am hoping to get this out this week.

**Comment by eamonnfaherty** [comment]
this is resolved in 0.26.0
