### ISSUE TITLE
Update requirements.txt

### ISSUE THREAD

**Issue by jaybutler328** [awslabs/aws-service-catalog-puppet#128]
Currently service-catalog-puppet has a lower better-boto and luigi requirement than service-catalog-factory.  

When running pip install aws-service-catalog-puppet i getting the following errors:  
ERROR: aws-service-catalog-factory 0.14.0 has requirement better-boto==0.13.0, but you'll have better-boto 0.11.0 which is incompatible.
ERROR: aws-service-catalog-factory 0.14.0 has requirement luigi==2.8.7, but you'll have luigi 2.8.6 which is incompatible.

If possible please update the requirements for service-catalog-puppet so both tools can coexist together in the same virtual environment.

**Comment by eamonnfaherty** [comment]
It is best to install the tools in different venvs.

For now the versions are aligned in 0.25.0.

I do try to keep them in sync but I do not normally release just for that.
