### ISSUE TITLE
Puppet GetTemplateSummary operation validation error

### ISSUE THREAD

**Issue by kahilof** [awslabs/aws-service-catalog-puppet#135]
Hi,

When trying to provision a launch a new product version, Puppet failed with below error. 

INFO MainThread Getting default parameters for for SC-938235781334-pp-uv4rhahugrev4 
ERROR: [pid 102] Worker Worker(salt=159641523, workers=10, host=7779925a057d, username=root, pid=98) failed    ProvisionProductTask(launch_name=zoom-api, portfolio=zoom-portfolio-zoom-components-portfolio, product=zoom-api, version=v2, product_id=prod-sn6ltgzh4efhg, version_id=pa-hn5bazdoatziy, account_id=938235781334, region=eu-west-2, puppet_account_id=938235781334, parameters=[{"name": "ElasticsearchDomainAutomatedSnapshotStartHour", "value": "0"}, {"name": "ElasticsearchDomainEbsVolumeSize", "value": "10"}, {"name": "NeptuneDBSubnetGroupName", "value": "zoom-dev-sng"}, {"name": "ElasticsearchVersion", "value": "6.4"}, {"name": "DBClusterIdentifier", "value": "zoom-dev-cluster"}, {"name": "AppName", "value": "zoom"}, {"name": "UserPoolName", "value": "ZoomUserPool"}, {"name": "ElasticsearchDomainClusterInstanceCount", "value": "1"}, {"name": "ZoomDiscoveryBucket", "value": "zoom-discovery-bucket-aws-scf"}, {"name": "ElasticsearchInstanceType", "value": "m4.large.elasticsearch"}, {"name": "SNSEmailSubscription", "value": "kahilo@amazon.co.uk"}, {"name": "CodeBucket", "value": "sc-factory-artifacts-938235781334-eu-west-2"}, {"name": "VpcName", "value": "zoom-dev"}], ssm_param_inputs=[], retry_count=1, ssm_param_outputs=[{"param_name": "zoom-api-vpcid", "stack_output": "VPCId"}, {"param_name": "zoom-api-pubsub1", "stack_output": "PublicSubnet0"}, {"param_name": "zoom-api-pubsub2", "stack_output": "PublicSubnet1"}, {"param_name": "zoom-api-prisub1", "stack_output": "PrivateSubnet0"}, {"param_name": "zoom-api-prisub2", "stack_output": "PrivateSubnet1"}, {"param_name": "zoom-api-sg", "stack_output": "DefaultSecurityGroup"}, {"param_name": "zoom-api-nepdbsg", "stack_output": "NeptuneDBSG"}, {"param_name": "zoom-api-nependpointadd", "stack_output": "NeptuneEndpointAddress"}, {"param_name": "zoom-api-nepreadendpoint", "stack_output": "NeptuneReadEndpointAddress"}, {"param_name": "zoom-api-nepsnstopic", "stack_output": "NeptuneSnsTopic"}, {"param_name": "zoom-api-nependpointport", "stack_output": "NeptuneEndpointPort"}, {"param_name": "zoom-api-snssub", "stack_output": "SNSEmailSubscription"}, {"param_name": "zoom-api-nepdbsgn", "stack_output": "NeptuneDBSubnetGroupName"}, {"param_name": "zoom-api-dbci", "stack_output": "DBClusterIdentifier"}, {"param_name": "zoom-api-esdomainarn", "stack_output": "DomainArn"}, {"param_name": "zoom-api-esdomainep", "stack_output": "DomainEndpoint"}, {"param_name": "zoom-api-essg", "stack_output": "SecurityGroupId"}, {"param_name": "zoom-discovery-bucket", "stack_output": "ZoomDiscoveryBucket"}, {"param_name": "zoom-user-pool", "stack_output": "UserPoolName"}]) 
Traceback (most recent call last): 
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 199, in run 
    new_deps = self._run_get_new_deps() 
  File "/usr/local/lib/python3.7/site-packages/luigi/worker.py", line 141, in _run_get_new_deps 
    task_gen = self.task.run() 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/luigi_tasks_and_targets.py", line 181, in run 
    cloudformation, f"SC-{self.account_id}-{provisioned_product_id}" 
  File "/usr/local/lib/python3.7/site-packages/servicecatalog_puppet/aws.py", line 75, in get_default_parameters_for_stack 
    StackName=stack_name, 
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call 
    return self._make_api_call(operation_name, kwargs) 
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call 
    raise error_class(parsed_response, operation_name) 
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the GetTemplateSummary operation: Stack with id SC-938235781334-pp-uv4rhahugrev4 does not exist

**Comment by eamonnfaherty** [comment]
Could you explain a little more about what you had been doing in your account?  Were you trying to update a product? Provision a new? 

From your output it looks like you were trying to update a product that was previously deployed.  It looks like the framework failed to update it as the CloudFormation stack was deleted.

**Comment by kahilof** [comment]
Hi Eamonn,

Thank you for your kind reply, I was able to solve it. Root cause is the old version of the product was tainted, when I deleted it I was able to deploy it successfully.
