### ISSUE TITLE
Configure the role that puppet use to connect to accounts

### ISSUE THREAD

**Issue by cfarida** [awslabs/aws-service-catalog-puppet#164]
Hi,

We would like to be able to configure an existing role that puppet uses to deploy the different service catalog products to the accounts.

This is useful if we have an existing organization that already have roles set up.

Thank you
Farid

**Comment by eamonnfaherty** [comment]
Hey @cfarida thanks for raising the request.

The trouble with this the user provided IAM role may not have the permissions needed to use the framework.  I am working towards a better definition of the IAM policy used.  Once that is done (2 - 3 weeks) I should be in a better position to comment on this.

**Comment by eamonnfaherty** [comment]
If you would like to restrict the role please see: https://github.com/awslabs/aws-service-catalog-puppet/issues/202

There are no plans to allow users to provide their own puppetrole.  It is best not to reuse roles for different tools, for example using the stackset role or the aws orgs access role.

You can use bootstrap spokes in ou https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/bootstrapping_spokes.html#groups-of-spokes

If you are unhappy with this please share a little more about your usecase as it may trigger another way I can help you.
