### ISSUE TITLE
GenerateShares does not handle a failed Share Accept, which can never be retried without intervention. 

### ISSUE THREAD

**Issue by apreed** [awslabs/aws-service-catalog-puppet#190]
https://github.com/awslabs/aws-service-catalog-puppet/blob/64b15774e3580ed1aa005e9ad1a9c9ea737c12a6/servicecatalog_puppet/luigi_tasks_and_targets.py#L1489

For example an AccessDenied exception on PuppetRole in a target account would cause a share to be created on the central Service Catalog, with a share to the target account, but the share would never be accepted. Because the share exists in the central Service Catalog, Puppet thinks the share exists and this causes a Deploy pipeline failure later (portfolio id not found in target)

**Comment by eamonnfaherty** [comment]
Thanks for raising this issue.  

I have two outstanding issues.  Once I have resolved those two I will look into this.

**Comment by eamonnfaherty** [comment]
Sorry for the delay.  This has been resolved in 0.51.0
