### ISSUE TITLE
Restrict Role Created by Service catalog puppet

### ISSUE THREAD

**Issue by KlodAyzak** [awslabs/aws-service-catalog-puppet#202]
Would it it be possible to restrict the role used and created by Service Catalog Factory? 
The objective would be to have least privilege roles.

**Comment by eamonnfaherty** [comment]
as of the 0.56.0 release, you can use a permission boundary for the puppetrole.

docs: https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/bootstrapping_spokes.html#restricting-spokes 

if you would like to see something else please reopen this issue.
