### ISSUE TITLE
May need to have wait time using the depends_on primitive

### ISSUE THREAD

**Issue by joaorodrig** [awslabs/aws-service-catalog-puppet#218]
The depends_on primitive may not be enough to make sure an instantiation is completed before the next one (e.g. SSM Parameters begin created, and used in the next instantiation). We suspect this may be due to the non-blocking nature of API calls (i.e. we don't wait for the resource to be created, instead we get a confirmation that the creation request has been successfully received by the AWS API)

**Comment by eamonnfaherty** [comment]
I have seen a delay of a second or two between setting an SSM parameter and it becoming available via a get.

**Comment by eamonnfaherty** [comment]
0.59.0 fixes this.
