### ISSUE TITLE
Less Permission of the Roles created for Puppet roles created on the master account

### ISSUE THREAD

**Issue by KlodAyzak** [awslabs/aws-service-catalog-puppet#223]
## Permission boundary support for the puppet role created in the master account
Upon the bootstraping of the master account, would it be possible to indicate a permission boundary to be attache to the roles created by the puppet (puppetDeployRole, PupperCodePipelineRole, PuppetProvisionningRole, PuppetGenerateRole)?

This feature would be similar to the https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/bootstrapping_spokes.html#restricting-spokes provided in the version 0.56

**Comment by eamonnfaherty** [comment]
I am going to add the following boundary capabilities:

- PuppetDeployRolePermissionBoundary
- PuppetCodePipelineRolePermissionBoundary
- PuppetProvisioningRolePermissionsBoundary
- CloudFormationDeployRolePermissionsBoundary
- PuppetGenerateRolePermissionBoundary
- SourceRolePermissionsBoundary

**Comment by eamonnfaherty** [comment]
resolved in 0.58.0
