### ISSUE TITLE
Feature - Ability to tag CloudFormation stacks to protect Puppet provisioned resources

### ISSUE THREAD

**Issue by tv-17** [awslabs/aws-service-catalog-puppet#225]
**Usecase: I want to prevent users from deleting/modifying any CloudFormation stacks used to baseline untrusted accounts.** 

Why tagging?
- Attribute based security control. https://docs.aws.amazon.com/IAM/latest/UserGuide/access_tags.html

An SCP or IAM role can then be applied to the account e.g.

`{
	"Version": "2012-10-17",
	"Statement": [
		{
			"Sid": "Statement1",
			"Effect": "Deny",
			"Action": [
				"cloudformation:*"
			],
			"Resource": [
				"*"
			],
			"Condition": {
				"StringEquals": {
					"aws:ResourceTag/managed-by-sctools": [
						"true"
					]
				},
				"ForAllValues:StringNotLike": {
					"aws:PrincipalArn": [
						"arn:aws:iam::*:role/servicecatalog-puppet/PuppetRole"
					]
				}
			}
		}
	]
}`

**Comment by eamonnfaherty** [comment]
This is a great, idea.  It will simplify the SCP policies quite a bit.  There is already a bit of a convention on the factory resources.

**Comment by eamonnfaherty** [comment]
resolved in 0.60.0
