### ISSUE TITLE
Exception: <Account> has been seen twice. 

### ISSUE THREAD

**Issue by tv-17** [awslabs/aws-service-catalog-puppet#228]
If I describe the accounts in such a way that the same account is present when puppet expands the manifest, puppet will fail on the generate shares stage.

For example my manifest file will look like:

- ou: '/Transition' 
    name: 'Transition' 
    default_region: *ParamDefaultRegion 
    regions_enabled: *ParamEnabledRegions
    tags: 
      - ou_name:Transition
      # - puppet:spoke 
      - baseline_rules:true 
      - aws_config:spoke
      - security:spoke
      - networking:spoke
      - adfs:true

- account_id: '1234567890' 
    name: 'TeamXYZ' 
    default_region: *ParamDefaultRegion
    regions_enabled: *ParamEnabledRegions
    tags: 
      - aws_account_name:team_xyz

This will fail with the error: 

`Exception: 1234567890 has been seen twice.  It was included due to it being in the ou: ou-xyzxyz`

**Comment by eamonnfaherty** [comment]
Use case here is that some policy should be applied to all accounts via ou: '/Transition' but account_id: '1234567890' declaration is applying addition policy.

**Comment by eamonnfaherty** [comment]
resolved in 0.63.0
