### ISSUE TITLE
Dependencies are not working

### ISSUE THREAD

**Issue by piersdb** [awslabs/aws-service-catalog-puppet#248]
Hello,

It looks like dependencies are not working as expected. I have a manifest with the following dependencies where the arrows represent the depends_on.
![graphviz](https://user-images.githubusercontent.com/7516609/73443325-5d4c1a00-434e-11ea-8883-9d147f3ada18.png)
However, these dependencies are not being followed - task d runs before task e. 

The expected reason is as follows:

When defining the tasks, puppet creates 1 layer of dependencies and then removes all dependencies from that dependency as shown in the code below. Call this the parent task, with child dependencies. The children have their dependencies removed. (dependency erasure) Each parent task is therefore passed a list of direct, connected dependencies which have no dependencies of their own.

https://github.com/awslabs/aws-service-catalog-puppet/blob/67f106677ce430839a27e088fc4b6cbc2ea2a5b1/servicecatalog_puppet/manifest_utils.py#L286-L297

To recreate the dependency chains, the parent `requires()` method dynamically recreates the children classes by instantiating a new ProvisionProductTask based on the list of children dependencies created in the previous code snippet as shown in the snippet below. These are instantiated without dependencies.

https://github.com/awslabs/aws-service-catalog-puppet/blob/67f106677ce430839a27e088fc4b6cbc2ea2a5b1/servicecatalog_puppet/workflow/provisioning.py#L151-L163

Luigi uses an internal instance cache for tasks in the task_register file. The expectation of the above snippet is presumably to instantiate the new class from the instance cache which has the full list of dependencies and thus transitive dependencies will work. However, the instance cache doesn't rely on the task signature to lookup previously created instances as expected, but rather the whole list of instantiation parameters as show in the snippet below. This means that significant parameters and insignificant parameters alike (e.g. the dependency list) are use to check if a previous instance exists. 

https://github.com/spotify/luigi/blob/2d5fbc844cbb13dcae36291a95dc1db649fc8b9a/luigi/task_register.py#L82-L101

This means that the `Register` class (the base class of `luigi.Task`) returns a new instance without dependencies rather than the stored instance with dependencies. As such, dependencies with more than 1 level deep will not resolve.

This also fails when all dependencies are explicit, i.e. the dependency graph is 1 level deep by specifying all dependencies in the depends_on tree. This is because the order of tasks is un-deterministic and thus a dependency could be run at any point. Looking back at the example graph, if the scheduler tries to run node b, sees that it depends on c,f,d,e and tries to run c, as c is a child dependency, it has had its dependencies erased, and thus will not run d or e first.

I am happy to help with a PR fix, I wanted to discuss advised approach.

Thank you!

**Comment by eamonnfaherty** [comment]
A fix for this was released yesterday in 0.68.0

Could you please retest.

**Comment by eamonnfaherty** [comment]
And close this when confirmed

**Comment by piersdb** [comment]
Ran through an initial series of tests, release 0.68.0 looks like it fixed this bug.

Thank you!
