### ISSUE TITLE
Spoke Products are orphaned from Hub products, requiring a Puppet run to sync them

### ISSUE THREAD

**Issue by apreed** [awslabs/aws-service-catalog-puppet#250]
The way that spoke local portfolios are created, the products from the imported portfolio are copied, which generates a new product ID.

If a new version is created in the hub, then a puppet run is required to make that version (provisioning artifact) available in the spoke. This requires puppet to be triggered on any product creation in the hub, which is heavy handed and slow.

The proposal is to associate products from imported portfolio directly to local portfolio, as then when updates are made in the hub, the local product receives the same update.

There is a backwards compatibility issue here, where given 2 products with the same name, but different product IDs, it's not possible to upgrade the local-only one with the latest version from the imported product.

**Comment by eamonnfaherty** [comment]
Sorry for the delay getting back to you on this.

I think this is a valuable addition but I cannot break backwards compatibility.

Also, the way this has been implemented may confuse existing users.

I think it would be nice to have this capability as a new capability and not a change to spoke-local-portfolios.

**Comment by apreed** [comment]
OK, noted.
I did handle the backwards compatibility by adding a new option that defaults to the current behaviour, but it's a fair comment that is should probably be a new capability rather than change to existing.

**Comment by apreed** [comment]
I've raised a new PR. I haven't gone as far as creating a new manifest block, the setting remains in spoke-local-portfolios.
The reason for this is that the new functionality is still dealing with spoke local portfolios - it's just adding a new method to get products into those portfolios. Creating a new block called "spoke-import-portfolios" is misleading, as it implies this is importing the whole portfolio, which is not true.

**Comment by eamonnfaherty** [comment]
this was resolved in 0.72.0
