### ISSUE TITLE
launches deploy_to by tags

### ISSUE THREAD

**Issue by none-soc** [awslabs/aws-service-catalog-puppet#254]
Hello,

I've not found in the documentation concerning manifest deployment of products based on tags (https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/designing_your_manifest.html) if it is possible to set multiple tags (tag name and regions) for the "deploy_to" section. All examples use only list with single tag.

for example:

    deploy_to:
      tags:
        - tag: type:prod
          regions: default_region
        - tag: scope:myscope
          regions: default_region

what will be the behavior if two or more tags are set, is it considered a logical AND or a logical OR list of tags :
- Does it deploys only for accounts with both tags or it deploys for accounts with at least one of the two tags ?
- Does it implies multiple deployment actions or a single deployment if both tags match an account ?

thanks in advance,

regards

**Comment by eamonnfaherty** [comment]
Hi, thanks for posting.

All items in the tags list are treated as an OR.

I have updated the docs to reflect this: https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/designing_your_manifest.html#tag-based-launches
