### ISSUE TITLE
BucketPolicy and TopicPolicy in shares template do not make use of principal org id

### ISSUE THREAD

**Issue by eamonnfaherty** [awslabs/aws-service-catalog-puppet#26]

**Comment by jordan-evans** [comment]
The current implementation refers to the OU ID, whereas it should refer to the Org ID.

**Comment by eamonnfaherty** [comment]
Thanks for the report. 

I have removed the release from pypi and will have a working version released this morning

**Comment by eamonnfaherty** [comment]
Fixed in 0.0.29
