### ISSUE TITLE
[Feature Request] Ability to unshare a portfolios from Puppet

### ISSUE THREAD

**Issue by KlodAyzak** [awslabs/aws-service-catalog-puppet#261]
Would it be possible to unshare a portfolio from puppet? 

It is currently possible terminate a product with an account but the related portoflio stays shared with the account hosting the product.

**Comment by eamonnfaherty** [comment]
resolved in 0.73.0

**Comment by KlodAyzak** [comment]
Awesome Thank you !

**Comment by KlodAyzak** [comment]
Hi, 

Is this documented? Could you please let us know how to use this feature. @eamonnfaherty
