### ISSUE TITLE
v0.76.1 - expand manifest.yaml fails with 'str' object has no attribute 'name'

### ISSUE THREAD

**Issue by RobBrazier** [awslabs/aws-service-catalog-puppet#280]
Running latest version 0.76.1, I've added the manifest.properties configuration to specify the versions externally to the launches configuration, however it seems to fail when figuring out which manifest.properties files to load

```
  manifest_utils.py line 47 in load
    f.name.replace('.yaml', '.properties'),
AttributeError: 'str' object has no attribute 'name'
```

I'll be honest, I'm new to python, but I'm thinking that `f` that's used [here](https://github.com/awslabs/aws-service-catalog-puppet/blob/master/servicecatalog_puppet/manifest_utils.py#L47) has been re-assigned [here](https://github.com/awslabs/aws-service-catalog-puppet/blob/master/servicecatalog_puppet/manifest_utils.py#L40) (even though it doesn't really make sense, but that's the only place I can see a string coming from) EDIT: reading up more on python's scopes it might make sense

# Steps to reproduce
1. Run `servicecatalog-puppet --info --expand manifest.yaml` with a `manifest.properties` (although I think the same error will occur if one is not present)

# Expected results
manifest.yaml successfully expanded

# Actual results
error thrown as above

**Comment by eamonnfaherty** [comment]
Thanks for raising the issue @RobBrazier and thanks for looking into the issue.  You are correct with your assessment.

I have released a fix for this in version 0.76.2
