### ISSUE TITLE
Failed provisioning causing a block to future runs due to changesets

### ISSUE THREAD

**Issue by eamonnfaherty** [awslabs/aws-service-catalog-puppet#283]
# Steps to reproduce
1. provisioning a product fails
1. run the pipeline again
1. 

# Expected results
pipeline should run without error

# Actual results
Get the error: Cannot delete ChangeSet in execution status EXECUTE_FAILED

**Comment by eamonnfaherty** [comment]
This is the way that AWS Service Catalog works.  We can add in automation that will check the stack status and terminate if in rollback complete but this will be a change in behaviour and would require a configuration option to opt into the change for existing installs.  Please +1 this if you would like to see this

**Comment by croccale** [comment]
+1

**Comment by eamonnfaherty** [comment]
added a flag for customers to opt into this feature.
