### ISSUE TITLE
botocore.errorfactory.InvalidParametersException: An error occurred (InvalidParametersException) when calling the ProvisionProduct operation: A stack named my-product already exists.

### ISSUE THREAD

**Issue by jordan-evans** [awslabs/aws-service-catalog-puppet#284]
Hi,

I'm using `0.76.2` and seeing this error during a Puppet execution in 1 or 2 accounts. `my-product` is a provisioned product that Puppet has previously deployed fine, but I see this error when trying to update the version of the product via Puppet.

```
botocore.errorfactory.InvalidParametersException: An error occurred (InvalidParametersException) when calling the ProvisionProduct operation: A stack named my-product already exists.
```

If I go into the target account and check Provisioned Products I can see `my-product` exists. It looks like instead of Puppet performing an update of an existing Product with the name of `my-product`, it is trying to provision a new one and getting the above error.

Not sure if this is some kind of pagination issue, but it suddenly manifested when updating the version of this provisioned product.

Thanks

**Comment by eamonnfaherty** [comment]
This looks like it could be an issue with AWS Service Catalog.  I will keep this open for others and will update when I have more details.

**Comment by eamonnfaherty** [comment]
This has been confirmed as an issue with AWS Service Catalog and not this framework. The latest version of this framework has a work around to avoid this from happening.
