### ISSUE TITLE
New SSM parameters are not being created : since 0.80.2

### ISSUE THREAD

**Issue by eamonnfaherty** [awslabs/aws-service-catalog-puppet#295]
Using version 0.80.2 (and since execution_mode was introduced), new ssm parameters added to outputs in launches configuration are not being added due to execution_mode=None in ProvisionProductTask

**Comment by nikolaigauss** [comment]
Hello! Regarding this issue, do we know if this is also affecting new params created in the manifest and added as "inputs" for the products? I'm asking because I need to update to 0.80.5 because of the fix of the associations, but at the same time I still need to use Params.

Thanks!

**Comment by eamonnfaherty** [comment]
sorry, this was fixed in a previous release and I did not close this issue.
