### ISSUE TITLE
servicecatalog-puppet-policies delays the execution quite a bit

### ISSUE THREAD

**Issue by nikolaigauss** [awslabs/aws-service-catalog-puppet#298]
In our environment we have 2 regions, and our puppet runs take about half an hour, we've been taking a look at the logs and we found that the step:
INFO MainThread Describing change set: servicecatalog-puppet-policies
Is taking quite long:
![image](https://user-images.githubusercontent.com/4080093/90009265-aa159380-dc95-11ea-8f82-a57aaa5a0cc4.png)
Is there a possibility to optimise this?

[execution.log.tar.gz](https://github.com/awslabs/aws-service-catalog-puppet/files/5062313/execution.log.tar.gz)

We're running the latest version, 0.80.5.

**Comment by eamonnfaherty** [comment]
I am not longer using change sets for the policy stack creation so this should be reduced.  If you are still seeing a delays or slowness here please reopen this issue and contact AWS support.
