### ISSUE TITLE
Deployment mode for large environments

### ISSUE THREAD

**Issue by costi1010** [awslabs/aws-service-catalog-puppet#299]
Was the Spoke deployment mode finally introduced officially in the framework ? i am referring to the branch https://github.com/awslabs/aws-service-catalog-puppet/pull/276
What would be the best way to overcome issues/limitations in big scale deployments ?

**Comment by eamonnfaherty** [comment]
Hi @costi1010 

Thanks for raising this issue.  The readthedocs build has been failing without notifications.  I have fixed the issue so the docs are now updating. 

Thanks again.

**Comment by eamonnfaherty** [comment]
To answer your question:

To overcome issues / limitations in big scale deployments it really depends on what your workflow looks like. 

If you are provisioning a lot of products in a lot of accounts and are unhappy with the effects of increasing the numbers of worker then I would recommend looking into the spoke execution mode.

If you want a fast workflow then I would recommend looking at toggling async on and using the list launches or the dashboard to monitor progress.  

I would be happy to chat to you about your workflow and give some advice.

**Comment by costi1010** [comment]
Cool, Thanx for the feedback. 
We'll test various constellations and come up with an architecture model that suits our needs. I'd really appreciate and i will be happy if we can chat and get some advices from your side on our workflow/architecture when we are ready with it.
Cheers and good day !!
