### ISSUE TITLE
Exclude functionality not working

### ISSUE THREAD

**Issue by toriancrane** [awslabs/aws-service-catalog-puppet#305]
# Steps to reproduce
1. Added a product launch with an exclude parameter to exclude an account within the OU specified.
2. Saved manifest file.
3. Triggered puppet pipeline.

# Expected results
Product to be launched in all accounts in the OU specified EXCEPT for the excluded account.

# Actual results
Product launched in all accounts INCLUDING the excluded account.

**Comment by eamonnfaherty** [comment]
this was resolved.  Turns out it was a misconfigured manifest file.
