### ISSUE TITLE
SCP Single Run - Terminal Failure State

### ISSUE THREAD

**Issue by NicPucacco** [awslabs/aws-service-catalog-puppet#317]
Please include a link to your expanded manifest, the full contents of your AWS CodeBuild output (see https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/using_the_cli.html#export-puppet-pipeline-logs)

Please ensure you are using the latest version and have run a validate command on your manifest file see (https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/using_the_cli.html#validate)

# Steps to reproduce
1. Vend an account

# Expected results
Account gets bootstrapped

# Actual results
Code build job: servicecatalog-puppet-single-account-run fails with terminate failure state

With error:

Traceback (most recent call last):
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/luigi/worker.py", line 199, in run
    new_deps = self._run_get_new_deps()
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/luigi/worker.py", line 141, in _run_get_new_deps
    task_gen = self.task.run()
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/servicecatalog_puppet/workflow/portfoliomanagement.py", line 541, in run
    cloudformation.create_or_update(
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/betterboto/cloudformation.py", line 62, in create_or_update
    raise e
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/betterboto/cloudformation.py", line 54, in create_or_update
    waiter.wait(StackName=stack_name)
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/botocore/waiter.py", line 53, in wait
    Waiter.wait(self, **kwargs)
  File "/root/.pyenv/versions/3.8.3/lib/python3.8/site-packages/botocore/waiter.py", line 320, in wait
    raise WaiterError(
botocore.exceptions.WaiterError: Waiter StackCreateComplete failed: Waiter encountered a terminal failure state

**Comment by NicPucacco** [comment]
Digging into the spoke account, the cloud formation error is much more understandable.

`The Principal with ARN arn:aws:iam::211941456693:role/OSS could not be found (Service: AWSServiceCatalog; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: e2eb6693-d9b1-4647-84c0-ca10e2cabddb; Proxy: null)`

It is trying to run the association task before it has run our IAM role creation products.
You can see the two attached CFN competition times, of the IAM roles and the association task in the images

![Screenshot 2020-11-02 at 21 01 33](https://user-images.githubusercontent.com/6772236/97921618-15ca4280-1d53-11eb-893e-2ba171b1a38b.png)
![Screenshot 2020-11-02 at 21 01 30](https://user-images.githubusercontent.com/6772236/97921624-16fb6f80-1d53-11eb-959d-801b3ec35149.png)

Any suggestions for work arounds? Or is there something missing the in manifest?

**Comment by NicPucacco** [comment]
Is it likely that the class (workflow/portfoliomanagement.py:471) CreateAssociationsForPortfolioTask needs the core products end tasks as a requirement in the requires function as well as the spoke local? 
Although it looks relationship related already :/

**Comment by eamonnfaherty** [comment]
Do you have a depends on in your manifest?  Can I see a copy of your manifest file please.

**Comment by NicPucacco** [comment]
Hmm yeah seems like that could fix, have made a change, will test tomorrow. Ty

**Comment by eamonnfaherty** [comment]
closing
