### ISSUE TITLE
Puppet pipeline fails following upgrade

### ISSUE THREAD

**Issue by mattsnell** [awslabs/aws-service-catalog-puppet#377]
I've worked out a procedure to help a team stand up a development environment and upgrade from factory v0.35.0 and puppet v0.44.2 to the current versions.  In the linked archive you'll find an export of the detailed process I used (sct.doc).  

Following the upgrade of puppet to v0.104.0, the _servicecatalog-puppet-pipeline_ runs repeatedly and fails each time.  The workaround is to manually release a change which clears the problem.  While not a blocker, it would be good to understand why.

In https://c1963bbc-c52f-11eb-b0e0-acde48001122.s3.amazonaws.com/sct-data.zip you'll find the expanded manifest and pipeline log output with the account numbers obfuscated.

# Steps to reproduce
1. Install puppet 0.44.2
1. Upgrade to 0.104.0

See linked document for full detail

**Comment by eamonnfaherty** [comment]
Creating associations in new versions of puppet is done in python for the puppet account.  this used to be in cloudformation.  Following the change, there is no 'wait' for the associations to propagate through AWS Service Catalog and a race condition exists.  running the pipeline twice resolves this issue as a work around.  a fix will be released later today for this.

**Comment by eamonnfaherty** [comment]
fixed in 0.104.1
