### ISSUE TITLE
Single Account Run can remove Organization shares

### ISSUE THREAD

**Issue by apreed** [awslabs/aws-service-catalog-puppet#387]
If a Puppet single account run is executed against a statically defined account in the manifest (ie an account that does not append or overwrite an OU level configuration) then the sc-factory-artifacts bucket policy gets replaced with a share for that single account only.

# Steps to reproduce
1. Create a manifest with an ou:  and an account_id: block in the accounts section
2. Execute puppet single account run against an account in the defined OU - bucket policy is set to share to the whole org
3. Execute puppet single account run against the account_id - bucket policy is rewritten to only share to the single account - ie bucket is unshared from the org 

# Expected results
Single account run should validate if bucket is already shared with target account, and *append* share to policy as required.

# Actual results
Bucket policy is removed and replaced with a more restrictive policy, meaning other accounts in the org lose access to the central artifact bucket

# *Workaround*
Add "organization:" to the statically defined account configuration as below

```
account_id: 123456789012
   organization: o-thingy
   default_region: eu-west-1
```

**Comment by eamonnfaherty** [comment]
Thanks for the fix and the tests. I have merged and released this: https://github.com/awslabs/aws-service-catalog-puppet/releases/tag/0.110.1
