### ISSUE TITLE
Puppet failing due to "ROLLBACK_COMPLETE"

### ISSUE THREAD

**Issue by Mladen-Trampic-SRB-1989** [awslabs/aws-service-catalog-puppet#416]
# Context

We try to create local shares with launch constraints, and from time to time during dev wrong role is referenced, eg no servicecatalog in role's trust relationship or, non existing role. -> causing CF to fails and render it into ROLLBACK_COMPLETE.

# Observation

From code I can see that in particular launch constraints Cloudformation stack is created with this part of code. 

https://github.com/awslabs/aws-service-catalog-puppet/blob/a93800d11f5c87a5f27378ff3388b5abe6b62265/servicecatalog_puppet/workflow/portfolio/constraints_management/create_launch_role_constraints_for_spoke_local_portfolio_task.py#L109-L117

Now, I can see from better-boto, that it should be possible to delete CFN stacks in ROLLBACK_COMPLETE state.

https://github.com/eamonnfaherty/better-boto/blob/486d3721ef7b1e641f1e223f41ebc17cde74b2fa/betterboto/cloudformation.py#L20-L47

I understand that it might be useful to leave CFN stack for troubleshooting events and understanding why it failed, but would be nice to have option to pass down parameter via manifest or somehow, else it is required to make additional scripting to cleanup several accounts.

The default Cloudformation setting is if new stack failed, it’ll delete all resources and keep status ROLLBACK_COMPLETE which is not updatable. [1]

# Summary

Feature / opinion request around passing down overriding param ShouldDeleteRollbackComplete=True to allow better-boto try do cleanup before retry.

Alternatively, maybe in this case is naive and safe to go with default True, since on next creation it should fail again. 

# Resources
[1] AWS Cloudformation Stack status codes : https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-cfn-describing-stacks.html#w2ab1c23c15c17c11

**Comment by Mladen-Trampic-SRB-1989** [comment]
PR Merged, closing.

**Comment by eamonnfaherty** [comment]
I have reopened this. 

It is merged to a new branch. I need to make some changes before releasing this. It is a change of behavior and so I need to wrap it on some config to not alter existing installs. I should have this released today.

**Comment by Mladen-Trampic-SRB-1989** [comment]
@eamonnfaherty , thank you for your amazing work.
