### ISSUE TITLE
Allow adding SSM outputs to an already provisioned launch

### ISSUE THREAD

**Issue by saukothari** [awslabs/aws-service-catalog-puppet#42]
When the AVM is launched and account is created, user decided that they needed to store the output from the stack to the SSM. 
Today we support that, provided the product is not yet deployed. But if the product was deployed and only SSM paramaters were updated in the manifest file, the deploy process skips it. 

It will be useful to support this.

**Comment by eamonnfaherty** [comment]
Renamed this issue and added enhancement label

**Comment by eamonnfaherty** [comment]
fixed in 0.1.0
