### ISSUE TITLE
Install of ServiceCatalog puppet failing in startInstall - CREATE_FAILED

### ISSUE THREAD

**Issue by NaelMachal** [awslabs/aws-service-catalog-puppet#422]
The installation of Service Catalog Puppet tool is failing with this event error exception : 

StartInstall | CREATE_FAILED | Received response status [FAILED] from custom resource. Message returned: CloudWatch Log Stream: 2021/09/01/[$LATEST]bec325b1e9504d3786fe49b0f139ccb5 (RequestId: d9cffca9-e205-4bf8-9d1f-2028eaf61ab8)
-- | -- | --

![Screenshot 2021-09-01 at 18 27 01](https://user-images.githubusercontent.com/89011756/131708872-583272d3-1f41-42a3-b1d9-2ee7dd2733d3.png)

I made sure to install the Factory tool before in the same region I tried to install the puppet (eu-central-1).

# Steps to reproduce
1.  Install the Factory tool from this template https://service-catalog-tools.s3.eu-west-2.amazonaws.com/factory/latest/servicecatalog-factory-initialiser.template.yaml ; Enabled Regions: eu-central-1 ; Stack Name: factory-initialization-stack
All other parameters by default.
1.  Install the Puppet tool from this template : https://service-catalog-tools.s3.eu-west-2.amazonaws.com/puppet/latest/servicecatalog-puppet-initialiser.template.yaml
Enabled Regions: eu-central-1 ; Stack Name: puppet-initialization-stack
All other parameters by default

The resources creation fails during the StartInstall for the puppet without any reason. 
I also tried the same process in eu-west-1 without anymore success.

**Comment by eamonnfaherty** [comment]
Hi,

Sorry for the issue.  This has now been fixed in 0.116.2.
