### ISSUE TITLE
Stacks validation is missing the CAPABILITY_AUTO_EXPAND

### ISSUE THREAD

**Issue by amirchoudhri** [awslabs/aws-service-catalog-puppet#431]
When using a "stack" within a Lambda function which requires the AUTO EXPAND capability, the validation fails. It looks like the CAPABILITY_AUTO_EXPAND is missing from the validation.

# Steps to reproduce
1. Use a cloudformation template which requires the CAPABILITY_AUTO_EXPAND capability (the guardduty spoke template is what i am using)
2. Use the "stack" type of deployment 

# Expected results
This should work but current fails see error below. I checked that the validation in puppet is missing the CAPABILITY_AUTO_EXPAND parameter.

# Actual results
[Container] 2021/09/16 15:22:50 Phase complete: INSTALL State: SUCCEEDED
[Container] 2021/09/16 15:22:50 Phase context status code:  Message:
[Container] 2021/09/16 15:22:50 Entering phase PRE_BUILD
[Container] 2021/09/16 15:22:50 Phase complete: PRE_BUILD State: SUCCEEDED
[Container] 2021/09/16 15:22:50 Phase context status code:  Message:
[Container] 2021/09/16 15:22:50 Entering phase BUILD
[Container] 2021/09/16 15:22:50 Running command servicecatalog-puppet validate manifest.yaml
Traceback (most recent call last):
  File “/root/.pyenv/versions/3.7.10/bin/servicecatalog-puppet”, line 8, in <module>
    sys.exit(cli())
  File “/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/click/core.py”, line 764, in __call__
    return self.main(*args, **kwargs)
  File “/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/click/core.py”, line 717, in main
    rv = self.invoke(ctx)
  File “/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/click/core.py”, line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File “/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/click/core.py”, line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File “/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/click/core.py”, line 555, in invoke
    return callback(*args, **kwargs)
  File “/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/servicecatalog_puppet/cli.py”, line 428, in validate
    manifest_commands.validate(f)
  File “/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/servicecatalog_puppet/commands/manifest.py”, line 114, in validate
    yamale.validate(schema, data, strict=False)
  File “/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/yamale/yamale.py”, line 43, in validate
    raise YamaleError(results)
yamale.yamale_error.YamaleError: Error validating data with schema ‘/root/.pyenv/versions/3.7.10/lib/python3.7/site-packages/servicecatalog_puppet/schema.yaml’
    stacks.sct-guardduty-spoke.capabilities.1: ‘CAPABILITY_AUTO_EXPAND’ not in (‘CAPABILITY_NAMED_IAM’,)
    stacks.sct-guardduty-spoke.key: Required field missing
[Container] 2021/09/16 15:22:51 Command did not exit successfully servicecatalog-puppet validate manifest.yaml exit status 1
[Container] 2021/09/16 15:22:51 Phase complete: BUILD State: FAILED
[Container] 2021/09/16 15:22:51 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: servicecatalog-puppet validate manifest.yaml. Reason: exit status 1

**Comment by eamonnfaherty** [comment]
fixed in https://github.com/awslabs/aws-service-catalog-puppet/releases/tag/0.127.0
