### ISSUE TITLE
Ability to Nuke the provisioned product

### ISSUE THREAD

**Issue by saukothari** [awslabs/aws-service-catalog-puppet#46]
Can we build the ability to Nuke the provisioned product from the spoke accounts? Just like we have for Factory?

something like:
All accounts:
servicecatalog-puppet nuke-product --protfolioname --productname --version --accounts all

Specific accounts:
servicecatalog-puppet nuke-product --protfolioname --productname --version --accounts '111111,2222222,3333333'

Specific OU
servicecatalog-puppet nuke-product --protfolioname --productname --version --accounts '/dev'

**Comment by eamonnfaherty** [comment]
this is available via the manifest in version 0.1.11

**Comment by eamonnfaherty** [comment]
if you want to terminate for a single account you can tweak your manifest file
