### ISSUE TITLE
GetCloudFormationTemplateFromS3 does not use region when building the S3 Key

### ISSUE THREAD

**Issue by eamonnfaherty** [awslabs/aws-service-catalog-puppet#461]
If you are using a transform in a stack the original template is used instead of the 'packaged' template.

**Comment by codeJack** [comment]
@eamonnfaherty would it be possible to expose the same level of service that we have for `products` for `stacks` ?

For instance [we can use Jinja template parameters such as `ALL_REGIONS` for products](https://aws-service-catalog-factory.readthedocs.io/en/latest/factory/building_your_pipelines.html#package) and that doesn't seem to be possible with stacks

**Comment by eamonnfaherty** [comment]
You will need to update to https://github.com/awslabs/aws-service-catalog-factory/releases/tag/0.74.0, rerun the factory pipeline and then rerun the stack pipelines.  This will ensure the correct region templates are available.  

There will be a new release of puppet shortly with more notes.

**Comment by eamonnfaherty** [comment]
you will need to update to puppet 0.140.0 for this fix.  there are no conf changes needed in puppet
