### ISSUE TITLE
Puppet Spoke template parameter types 

### ISSUE THREAD

**Issue by ricmerr** [awslabs/aws-service-catalog-puppet#472]
Please include a link to your expanded manifest, the full contents of your AWS CodeBuild output (see https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/using_the_cli.html#export-puppet-pipeline-logs)

Please ensure you are using the latest version and have run a validate command on your manifest file see (https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/using_the_cli.html#validate)

When using the spoke execution method for Puppet I hit an error whereby the codebuild project is attempting to retrieve SSM params for partition/puppet role/puppet role path. Checked the params and they type is set to parameter store rather than plaintext:

          - Name: PARTITION
            Type: PARAMETER_STORE
            Value: !Ref AWS::Partition
          - Name: PUPPET_ROLE_NAME
            Type: PARAMETER_STORE
            Value: !Ref PuppetRoleName
          - Name: PUPPET_ROLE_PATH
            Type: PARAMETER_STORE
            Value: !Ref PuppetRolePath
# Expected results 
           The codebuild deploy in spoke project should run

# Actual results
           I get the following: [Container] 2022/02/18 16:25:04 Phase context status code: Decrypted Variables Error Message: AccessDeniedException: No access to reserved parameter name: aws.

**Comment by eamonnfaherty** [comment]
this has been fixed.
