### ISSUE TITLE
SSM Parameters for Spoke Execution mode

### ISSUE THREAD

**Issue by ricmerr** [awslabs/aws-service-catalog-puppet#473]
# Steps to reproduce
1.  Set a launch to execution mode spoke which creates SSM parameters from stack outputs
2. Execute the servicecatalog-puppet-pipeline

# Expected results
SSM parameters are created as anticipated and can be consumed during the pipeline run

# Actual results
I do not see ssm parameters in the Puppet account or the spoke account. I have tried specifying account_id: puppetaccountid

It would be great to have these spoke ssm parameters in the puppet account parameter store. This would be ideal to enable us to be able to have a single source of ssm params

**Comment by eamonnfaherty** [comment]
this is resolved in 0.147.0
