### ISSUE TITLE
New puppet version expects new ssm parameter

### ISSUE THREAD

**Issue by koenigmartin** [awslabs/aws-service-catalog-puppet#481]
When updating the puppet from 0.139.0 to 0.145.0 the pipeline failed due to a missing ssm parameter.

Checking the code we found that this seems to be the cause:
> SERVICE_CATALOG_PUPPET_MANIFEST_SSM_PREFIX = "/servicecatalog-puppet/manifest"

Creating the ssm parameter (containing a '#') did the trick. Though better handling for this issue would be appreciated, for example allowing to ignore this parameter if not used via flag. 

# Steps to reproduce

1. check that the ssm parameter "/servicecatalog-puppet/manifest" is not in place in the puppet account
2. deploy puppet with version 0.139.0
3. run the pipeline to validate its successful
3. update puppet with version 0.145.0
4. run the puppet pipeline and it will fail

Best regards, Martin

**Comment by eamonnfaherty** [comment]
Hey Martin, 

Thanks for reporting this and sorry you have hit this issue.

Would you mind sharing the error you were seeing?

Thanks

**Comment by koenigmartin** [comment]
Hi Eamonn,
this was the error message thrown:
![puppet](https://user-images.githubusercontent.com/53942671/156116243-9a3571a0-0500-47c1-8d75-804b1455cd92.png)

I noticed that my initial statement might not have been accurate. I think adding the parameter and upgrading to a newer version of the puppet (0.151.0) did solve the issue (not just adding the parameter as stated in the initial comment).
Best regards, Martin

**Comment by eamonnfaherty** [comment]
Hey Martin,

This issue you encountered was already fixed and unrelated to SSM.  I would recommend removing the SSM parameter you created when you get a chance.

For others who may read this issue: the SSM parameter does not need to be created.  We only ever retrieve parameters from that path using get_parameters_by_path which does not raise an exception if no parameters match the path.

**Comment by koenigmartin** [comment]
I can confirm that after updating to 0.154.0 the paramter was no longer required.
