### ISSUE TITLE
Moving execution mode to "spoke" causes ResourceNotFoundException on "older" accounts

### ISSUE THREAD

**Issue by mdaehnert** [awslabs/aws-service-catalog-puppet#497]
Hi SCT team,

please find our error below. It would be great to get some details on why the error happens.

# Hints about solution
* We use Puppet since version 0.89.0 (2020) and migrated it last month to LATEST.
* As production runs now take 1h+ we want to move to spoke execution mode.
* The error appears on accounts which were created and bootstrapped before Puppet version upgrade.
* Do we miss anything to have the Spoke execution mode been possible on "older" accounts?

# Expected results
Puppet should run without errors.

# Actual results
When changing manifest entries to ```execution: spoke``` it fails.

```log
2022-03-25T12:41:19.068Z botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the StartBuild operation: Project cannot be found: arn:***:codebuild:eu-west-1:123456789012:project/servicecatalog-puppet-deploy-in-spoke
```

**Comment by eamonnfaherty** [comment]
Spoke execution mode was developed and released around 18 months ago.  If you have bootstrapped spokes before then you will need to rebootstrap.

This is the only cause to date for you needing to rebootstrap and going forward another route has been taken to avoid this from happening again.

**Comment by mdaehnert** [comment]
Thank you. I will follow this procedure of bootstrapping accounts again (https://service-catalog-tools-workshop.com/installation/50-bootstrapping.html). I will close the issue and leave it for others as reference.

**Comment by mdaehnert** [comment]
I also found the official documentation. My bad. Thank you @eamonnfaherty 

https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/execution_modes.html#spoke

Note
This will require you to bootstrap your spokes again if you bootstrapped your spokes with a version prior to 0.78.0 - which was July 8, 2020. You can check the version of the spoke in AWS SSM Parameter store (a parameter named service-catalog-puppet-spoke-version in your home region should be present). If you need to bootstrap your spokes again you can bootstrap each in the same way you initially did it otherwise you can use the AWS Codebuild project servicecatalog-puppet-bootstrap-spokes-in-ou
