### ISSUE TITLE
Stuck: Need to wait for stack completion

### ISSUE THREAD

**Issue by jordan-evans** [awslabs/aws-service-catalog-puppet#50]
When deploying an update to a product that was a dependency to another product, the build hung on the below log line:

`Need to wait for stack completion`

The build waited on this step for 10 minutes before I stopped it, even though the stack finished deploying in about 30 seconds. 

A subsequent run of the pipeline (after stopping the initial hung build) succeeds.

Looks like the waiter never returns?

**Comment by eamonnfaherty** [comment]
Thanks for reporting this. I will try to recreate it.

**Comment by eamonnfaherty** [comment]
Hi @jordan-evans 

I have not been able to recreate this.  

I followed these steps:
- product a is v1 
- product b is v2
- product a depend on b
- change b version from v1 to v2

What sort of resources where changing?  Was it adding resources, removing resources or changing existing resources?

**Comment by jordan-evans** [comment]
Can't replicate this again so calling it a one-off and closing for now.
