### ISSUE TITLE
Manual approval step in the pipeline

### ISSUE THREAD

**Issue by eamonnfaherty** [awslabs/aws-service-catalog-puppet#53]
Could you please add a manual approval step into the pipeline before the deployment occurs?

**Comment by jordan-evans** [comment]
I'd maybe go a step further here in that it would be great if Puppet could produce a report of changes that will occur in the next run, and prompt the user to review & approve them. Think this also brings together the suggestion in #52

**Comment by jordan-evans** [comment]
I think Puppet already executes a ChangeSet on every launched product, so maybe reporting which ones have been marked for change, and what resources would be updated would be good? Very similar to the output you get from a `terraform plan` maybe?

**Comment by eamonnfaherty** [comment]
0.16.0 addresses this.  Here are the docs: https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/getting_up_and_running.html#configuring-your-puppet
