### ISSUE TITLE
Portfolio Associations broken for unconditional interaction

### ISSUE THREAD

**Issue by kunzt-aws** [awslabs/aws-service-catalog-puppet#535]
We are using a IAM role to access the service catalog in a spoke account. The role is created during account onboarding/bootstrapping process.

To get the IAM role associated as a principal, we used the association coming with Puppet. Initially it worked fine but now we ran into problems as we hat to re-deploy the IAM role.
Based on the Security capabilities of AWS, all the references/associations get outdated when the role is removed.

However, this state does not get recognized by the Service Catalog Puppet as the code of the Service Catalog Puppet hasn't changed and the state of the Association CloudFormation template has not changed. However, the role is not association to the Portfolio.

Situation could be resolved by re-applying the associations for the impacted portfolios. As of today, this capability is not included in the solution. Also, the associations only cannot be removed from the portfolio distribution.

Only way to resolve the situation using an automated approach is to remove the portfolio share and (re-)add it again in the Service Catalog Puppet. This is very impactful and affects a lot more services than required.

**Comment by eamonnfaherty** [comment]
Thanks for reporting this.  The report is a little confusing. 

For the steps to reproduce I think I am clear up to the following:

Create an IAM role named foo
Create a portfolio association for the role named foo
Delete the IAM role named foo
Create a second IAM role also named foo

Is this correct?  If so, what happens next and what is the behaviour you were expecting?

**Comment by kunzt-aws** [comment]
Thanks for getting back to me that quickly. Here's the information to re-produce the issue:

1. Create an IAM role named foo
2. Create a portfolio association for the role named foo
3. Delete the IAM role named foo

From this point, the association for the IAM role is not valid anymore although still included in the configuration (manifest).
This situation cannot be resolved other than un-sharing the portfolio ('status: terminated') and re-sharing the portfolio (assuming that the IAM role has been created in the meantime)

**Comment by kunzt-aws** [comment]
> Thanks for getting back to me that quickly. Here's the information to re-produce the issue:
> 
> 1. Create an IAM role named foo
> 2. Create a portfolio association for the role named foo
> 3. Delete the IAM role named foo
> 
> From this point, the association for the IAM role is not valid anymore although still included in the configuration (manifest). This situation cannot be resolved other than un-sharing the portfolio ('status: terminated') and re-sharing the portfolio (assuming that the IAM role has been created in the meantime)

Thanks for getting back to me that quickly. Here's the information to re-produce the issue:

Create an IAM role named foo
Create a portfolio association for the role named foo
Delete the IAM role named foo
From this point, the association for the IAM role is not valid anymore although still included in the configuration (manifest).
This situation cannot be resolved other than un-sharing the portfolio ('status: terminated') and re-sharing the portfolio (assuming that the IAM role has been created in the meantime)

**Comment by eamonnfaherty** [comment]
I am asking as I know provisioned products are bound to the role id of the IAM role.  When you recreate a role with the same name it has a new role id and so the provisioned product belongs to a different role id with the same role name.   Without knowing what specifically is going wrong I cannot help. What are you seeing go wrong within AWS? What are you trying to do when it goes wrong? How do you know the IAM role is not valid anymore?

**Comment by eamonnfaherty** [comment]
this was taken offline.  When viewing an association for a portfolio in the AWS Service Catalog console where the principal was recreated the user experience does not show the new principal details in the same way it showed the old principal details.

This is out of scope for this project.
