### ISSUE TITLE
SCFramework puppet product termination issue

### ISSUE THREAD

**Issue by shydhanya** [awslabs/aws-service-catalog-puppet#546]
SCPuppet version 0.180.1 failed to terminate the products. 
New version 0.185.0 also failing with same issue. 

Downgraded the version to 0.175.0 to fix the problem. 

**Error:** No detailed log about failure is provided except the error in below snippet

<img width="1705" alt="image" src="https://user-images.githubusercontent.com/37020616/183530290-dd8e7c9b-13e4-413c-888b-88e97209f1d7.png">

# Expected results
Expect product to be terminated or unshared from child accounts.

# Actual results
SCPuppet pipeline failed to complete

**Comment by eamonnfaherty** [comment]
fixed in 0.186.0

**Comment by shydhanya** [comment]
Thankyou. It worked.
