### ISSUE TITLE
Regions parameter in defaults section of manifest file failed with None error

### ISSUE THREAD

**Issue by shydhanya** [awslabs/aws-service-catalog-puppet#547]
Puppet pipeline fails if I have regions_enabled or default_region in defaults: section of the file.
I am using puppet version 0.175.0 

However, it works fine if I move these 2 parameters to accounts: section. 
I am copying these 2 parameters across 65+ accountid in production.

I tried to reproduce the same issue in Dev account with same version, unfortunately this issue is not occurring in development account. 

Could you please help to fix this problem?

```

> File   "*root*.pyenv*versions*3.7.13*lib*python3.7*site-packages*servicecatalog_puppet*manifest_utils.py",   line 1237, in get_account_ids_and_regions_used_for_section_item
> 
> for   task in self.get_tasks_for(puppet_account_id, section_name, item_name):
> File   "*root*.pyenv*versions*3.7.13*lib*python3.7*site-packages*servicecatalog_puppet*manifest_utils.py",   line 958, in get_tasks_for
> for region_enabled in   account.get("regions_enabled"):
> TypeError: 'NoneType' object is not   iterable

```

**Comment by eamonnfaherty** [comment]
Can you please share your manifest file.

**Comment by shydhanya** [comment]
<img width="689" alt="image" src="https://user-images.githubusercontent.com/37020616/184558389-99754943-1682-4359-842e-7fb89685277b.png">

**Comment by eamonnfaherty** [comment]
the following works in 0.186.0:
``` yaml
defaults:
  accounts:
    default_region: "eu-west-1"
    regions_enabled:
      - "eu-west-1"
      - "eu-west-2"
      - "eu-west-3"
      - "us-west-1"
      - "us-east-1"

accounts:
  - account_id: "${AWS::PuppetAccountId}"
    name: "puppet-account"
    tags:
      - "role:sct"
```
