### ISSUE TITLE
puppet_account_id account id returning None due to missing environment variables

### ISSUE THREAD

**Issue by nathanberry97** [awslabs/aws-service-catalog-puppet#555]
Please include a link to your expanded manifest, the full contents of your AWS CodeBuild output (see https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/using_the_cli.html#export-puppet-pipeline-logs)

Please ensure you are using the latest version and have run a validate command on your manifest file see (https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/using_the_cli.html#validate)

# Steps to reproduce
1.  with the latest release when running the following command within codebuild it is returning None for puppet_account_id. 
2. Command: servicecatalog-puppet bootstrap-spokes-in-ou $OU_OR_PATH $IAM_ROLE_NAME $IAM_ROLE_ARNS 
3. The error is due to the newest updates to servicecatalog_puppet/config.py which is now assuming within the shell environment we have the vars setup which are located in servicecatalog_puppet/environment_variables.py
4. we can give the correct account number by updating the buildspec environment variable "SCT_PUPPET_ACCOUNT_ID" 
5. i.e. export SCT_PUPPET_ACCOUNT_ID=accountNumber added within the buildspec
6. But this just causes even more issues, I'm assuming we are missing some setup criteria of the environment vars but cannot find any documentation on this

The following image shows the difference between the update and previous release:
![updates to package](https://user-images.githubusercontent.com/54477304/188132389-950b000d-683f-4ad1-8247-3c7484d9431d.PNG)
Basically the new release is depending on there being environment variables setup within the shell which is causing the error due to them not being present 

1. We then tried to roll back to version 0.185.0, codebuild works as expected but we ran into another problem as we wanted to revert the cloudformation puppet-initialization-stack back to 0.185.0 
2. but as the url within the docs is pointing to latest: https://service-catalog-tools.s3.eu-west-2.amazonaws.com/puppet/latest/servicecatalog-puppet-initialiser.template.yaml
3. I was wondering if it is possible to have this point towards a older version i.e. 0.185.0 

# Expected results
sts:AssumeRole on resource: arn:aws:iam::{AccountNumber}:role/servicecatalog-puppet/PuppetRole

# Actual results
not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::None:role/servicecatalog-puppet/PuppetRole

I'm assuming the issue is due to missing setup requirements to populate the environment vars within codebuild, any help would be greatly appreciated

**Comment by eamonnfaherty** [comment]
Thanks for raising this issue and sorry for the disruption.

This is fixed in version 0.188.0.

There is a page in the docs on how to install specific versions https://service-catalog-tools-workshop.com/installation/installing-specific-versions.html If may be useful for your question

**Comment by nathanberry97** [comment]
Amazing thank you Eamonn!
