### ISSUE TITLE
Product Termination in 0.193.0

### ISSUE THREAD

**Issue by shydhanya** [awslabs/aws-service-catalog-puppet#561]
Termination Issue: `status: terminated` action in manifest file, didn't unshare the product from child account.

**Comment by eamonnfaherty** [comment]
can you share your build logs and your manifest file.

**Comment by shydhanya** [comment]
Manifest file content -
<img width="399" alt="image" src="https://user-images.githubusercontent.com/37020616/191230688-034178f0-15fb-4c5d-8c35-45e9e85b8c92.png">

Error Log - 
<img width="1641" alt="image" src="https://user-images.githubusercontent.com/37020616/191231163-61dc70bb-b151-4bc3-9754-14cae43bc5ab.png">


Product availability in hub account and is shared to child account -  
<img width="711" alt="image" src="https://user-images.githubusercontent.com/37020616/191231366-24646837-54b0-4fb3-bebb-2eb160d0418c.png">

**Comment by shydhanya** [comment]
[puppet-193 and 185-product termination log.docx](https://github.com/awslabs/aws-service-catalog-puppet/files/9615329/puppet-193.and.185-product.termination.log.docx)

#Attached detailed log file. Product termination build log for both version 0.193 and 0.185
