### ISSUE TITLE
Puppet 0.193.0 product update version failure

### ISSUE THREAD

**Issue by shydhanya** [awslabs/aws-service-catalog-puppet#562]
# Product update failed with exception 'Artifact not exist' even though product version exists. 

# Product Available Screenshot
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/37020616/189011033-a372a2fd-0030-4a71-b60d-bd09064630cf.png">

# Puppet Exception
<img width="1650" alt="image" src="https://user-images.githubusercontent.com/37020616/189011221-9718c0c5-0774-406a-8f48-be0c9423f6a9.png">

**Comment by eamonnfaherty** [comment]
can you share your full build logs and your manifest file please.

**Comment by shydhanya** [comment]
[puppet-193-provisioning-log.docx](https://github.com/awslabs/aws-service-catalog-puppet/files/9612026/puppet-193-provisioning-log.docx)


Build log in attached file.

**Comment by eamonnfaherty** [comment]
Is this still an issue?

**Comment by shydhanya** [comment]
This issue didnt occur in 0.194. I am good.
