### ISSUE TITLE
CodePipeline is using an incorrect role name argument

### ISSUE THREAD

**Issue by UnSciPreneur** [awslabs/aws-service-catalog-puppet#568]
We are following the [2021 Workshop](https://service-catalog-tools-workshop.com/2021-workshop/100-removing-the-default-networking/30-deploying-the-lambda.html) guide in a vanilla organization/account. In the step 'Removing the default networking' / 'Deploying the Lambda' the `servicecatalog-puppet-pipeline` keeps failing with the following log message

```
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the CreateStack operation: Role arn:***:iam::$ACCOUNT_ID:role***PuppetStackRole is invalid or cannot be assumed
```
Looking at the CloudTrail logs we have found that the service tries to assume a role with resource arn 
```
arn:aws:sts::$ACCOUNT_ID:assumed-role/CodePipelineRole/1663743811777
```
Here the `1663743811777` part keeps changing from invocation to invocation and most probably matches the current unix timestamp.

**Comment by eamonnfaherty** [comment]
sorry for the delay looking at this.

I think the diagnosis may be incorrect. 

When provisioning stacks there is a pre req task that should be executed.  from viewing your logs this was not scheduled / run and so the iam role is not available in the spoke.

**Comment by eamonnfaherty** [comment]
this is now resolved.
