### ISSUE TITLE
Performance drop (Status pending on code build lasting nearly two hours before puppet runs)

### ISSUE THREAD

**Issue by nathanberry97** [awslabs/aws-service-catalog-puppet#591]
When deploying our resources with puppet the performance has dropped significantly compared to 2 months ago, with our deployment time increasing on average from around 30 minutes or so to our most recent builds which are coming close to 2 hours and 30 minutes.

We do deploy a few more packages since then and have a few more aws accounts to deploy too, but I don't understand how this would result in such a dramatic time increase.

When looking into the log's majority of the time the resources are stuck on pending, once the process starts around the 2 hour mark it completes the build relatively quick.

# Expected results

To not have the code build stuck on pending each time we deploy new resources for nearly two hours

# Actual results

When deploying the resources are stuck on pending for a long time compared to when we were deploying our resources a few months ago 

Any suggestions to increase the performance would be great as puppet is just getting increasingly slower with each build

**Comment by eamonnfaherty** [comment]
Hey @nathanberry97 thanks for raising this and sorry for the issue you are encountering.  

Could you please confirm which version you are using?

The newer versions of puppet (since 0.195.0) should provide much better performance.

**Comment by nathanberry97** [comment]
I've check and seems we are using an older version 0.188.0, I'll get that updated to the newer version.

Thank you for getting back to me Eamonn much appreciated
