### ISSUE TITLE
Association of SSO role in products

### ISSUE THREAD

**Issue by shydhanya** [awslabs/aws-service-catalog-puppet#592]
We need to associate a SSO role with dynamic values in role name to products during deployment. 

### **Portfolio Association -** 
![image](https://user-images.githubusercontent.com/37020616/201906209-c007f239-a171-41dd-bb8e-5f75a878538a.png)

### **Error-** 
![image](https://user-images.githubusercontent.com/37020616/201906655-53adbdd9-331b-400e-ba18-fe1806fa71f7.png)

### **Product Association -** 
![image](https://user-images.githubusercontent.com/37020616/201906981-72048c6f-7832-4eeb-a6bb-e17f7aeaee76.png)

### **No error, but role is not associated in spoke accounts.** 
![image](https://user-images.githubusercontent.com/37020616/201907530-520bc8c0-202e-4706-afa8-5efad7df9709.png)

# Expected results
Existing SSO Role with prefixed static values should be associated to products in specific account. 

# Actual results
Puppet pipeline is successful, but the SSO roles are not associated.

**Comment by shydhanya** [comment]
**Cloudformation template which has failed while adding role to Portfolio association -** 

AWSTemplateFormatVersion: '2010-09-09'
Description: 
    Associations for Provision-CodeCommit-Repository-test-vend-port
    {"version": "XXX", "framework": "servicecatalog-factory", "role": "portfolio-associations"}

Conditions:
  ShouldDoAnything: !Equals [ true, false]

Resources:
  NoOp:
    Type: AWS::S3::Bucket
    Condition: ShouldDoAnything


  Association1:
    Type: AWS::ServiceCatalog::PortfolioPrincipalAssociation
    Properties:
      PrincipalARN: !Sub "arn:aws:iam::${AWS::AccountId}:role/servicecatalog-puppet/PuppetRole"
      PortfolioId: port-rus5qocyoexp4
      PrincipalType: IAM

**Comment by eamonnfaherty** [comment]
the use of wildcard only supports roles at the moment and not users
