### ISSUE TITLE
Portfolio or Product tag is not available in end products

### ISSUE THREAD

**Issue by shydhanya** [awslabs/aws-service-catalog-puppet#608]
Tags are created by developers for portfolio and products in their respective configuration files. It is available in hub, however below are my observation in spoke accounts - 

**Launches -** 
1. Products list or Provisioned products has default auto tags from SCT and it missed to retain the custom tags added by developer.
2. CFN stack also has auto tags from SCT. 
<img width="976" alt="image" src="https://user-images.githubusercontent.com/37020616/204307721-2c4bf1fd-ee24-4eeb-9eb6-36481679c29d.png">
3. Product tag(highlighted in red) added by developer is missing in provisioned product tag list(as in above screenshot)-
<img width="470" alt="image" src="https://user-images.githubusercontent.com/37020616/204309010-099c0e39-af9a-4e3c-99ad-c462910a226c.png">
 
**Spoke-local-portfolio-**
1. Product list has custom tags as expected. But when the product is launched it is overwritten by SCT autotags.
2. CFN stack also has auto tags from SCT. 
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/37020616/204320650-3c458322-9ca9-431a-bd95-8a691f340dab.png">

**Expected:**
We expect SCT to retain the tags from portfolio and products to the end resources launched in AWS. End products or resources (launched or deployed) by SCT should include tags defined by developer in portfolio as well as in products. 
If auto-tags can be consistent for both launch and spoke-local-portfolio type, it helps to define some policy to restrict user access.

**Comment by eamonnfaherty** [comment]
I am not sure your original issue is a defect.

If you specify tags within the YAML files of factory the provisioning artefacts should have those tags.  When you provision a product you will not have the tags.

**Comment by eamonnfaherty** [comment]
Your second post is listing two issues which I have raised here https://github.com/awslabs/aws-service-catalog-puppet/issues/611
