### ISSUE TITLE
Launches are not respecting tag options

### ISSUE THREAD

**Issue by eamonnfaherty** [awslabs/aws-service-catalog-puppet#611]
spilt from https://github.com/awslabs/aws-service-catalog-puppet/issues/608

## Steps
1. create a portfolio using factory that has tag options
2. set tag options sharing to true
3. provision a product in a spoke via a launch 

## expected
1. provisioned product should have tags from tag options

## actual
1. provisioned product does not have tags from tag options

**Comment by eamonnfaherty** [comment]
just ran a test of launching a product in the puppet account and it worked as expected.

**Comment by eamonnfaherty** [comment]
just ran a test of a launching a product in a non puppet account and it worked as expected.

**Comment by eamonnfaherty** [comment]
@shydhanya Can you please confirm you are seeing this issue.  

If you are seeing this issue can you check the tag options on the imported portfolio within the spoke account to see if the correct tag options are appearing there.

**Comment by shydhanya** [comment]
Terminated and recreated product worked :) Thanks. 
<img width="423" alt="image" src="https://user-images.githubusercontent.com/37020616/205759652-1bf75d8f-0195-424b-8277-0b754b3d6aa2.png">
