### ISSUE TITLE
Problem to update Puppet  

### ISSUE THREAD

**Issue by faritvidalGL** [awslabs/aws-service-catalog-puppet#615]
Please include a link to your expanded manifest, the full contents of your AWS CodeBuild output (see https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/using_the_cli.html#export-puppet-pipeline-logs)

Please ensure you are using the latest version and have run a validate command on your manifest file see (https://aws-service-catalog-puppet.readthedocs.io/en/latest/puppet/using_the_cli.html#validate)

# Steps to reproduce
- Currently this is the version we have in place  0.143.0 when I tried to update to the latest version which in this case is 0.210.0 using the method that comes in this link:

https://service-catalog-tools-workshop.com/upgrading/service-catalog-puppet.html

- The pipeline failed without much information in the error to trobuleshoot
- For security reasons I can't attach the manifest file
- But if I attach the output log of the pipeline `servicecatalog-product-puppet-initialiser`

# Expected results
 - Failed

# Actual results

[log-events-viewer-result.csv](https://github.com/awslabs/aws-service-catalog-puppet/files/10196637/log-events-viewer-result.csv)

**Comment by eamonnfaherty** [comment]
Fresh installs and upgrades where users are not using  

resulted in this error:


```
Traceback (most recent call last):
--
247 | File "/root/.pyenv/versions/3.9.12/bin/servicecatalog-puppet", line 8, in <module>
248 | sys.exit(cli())
249 | File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/click/core.py", line 764, in __call__
250 | return self.main(*args, **kwargs)
251 | File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/click/core.py", line 717, in main
252 | rv = self.invoke(ctx)
253 | File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/click/core.py", line 1137, in invoke
254 | return _process_result(sub_ctx.command.invoke(sub_ctx))
255 | File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/click/core.py", line 956, in invoke
256 | return ctx.invoke(self.callback, **ctx.params)
257 | File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/click/core.py", line 555, in invoke
258 | return callback(*args, **kwargs)
259 | File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/servicecatalog_puppet/cli.py", line 347, in bootstrap
260 | bootstrap_commands.bootstrap(**parameters)
261 | File "/root/.pyenv/versions/3.9.12/lib/python3.9/site-packages/servicecatalog_puppet/commands/bootstrap.py", line 73, in bootstrap
262 | except events.exceptions.ResourceNotFoundException:
263 | UnboundLocalError: local variable 'events' referenced before assignment
```

This should be resolved in version 0.213.1
