### ISSUE TITLE
Update CodeBuild Containers used to aws/codebuild/standard:5.0 or 6.0

### ISSUE THREAD

**Issue by peteawood** [awslabs/aws-service-catalog-puppet#641]
We're using Puppet 0.171.0 and received a notification from AWS regarding the usage of the Ubuntu 4.0 CodeBuild image:

> We are reaching out to you because you ran a build using the Ubuntu standard 4.0 [1] Docker Image, in the last 30 days.
> 
> Starting March 30, 2023, AWS CodeBuild will be moving these images to an unsupported status and they will not be cached on the build hosts anymore.
> 
> You may continue using these images for your builds, but will notice an increase in provisioning latency after March 30, 2023.

In our spoke accounts this is being caused by the servicecatalog-puppet-deploy-in-spoke CodeBuild project where we are running in Spoke execution mode.

https://github.com/awslabs/aws-service-catalog-puppet/blob/5a2c35926934080d5c5cca000d3e06ed3b499760/servicecatalog_puppet/servicecatalog-puppet-spoke.template.yaml#L140

Please could the above be upgraded to 5.0 or 6.0? I also see 4.0 referenced in the following locations:

https://github.com/awslabs/aws-service-catalog-puppet/blob/288cf1cb9a4620f704cb2e3ded2cb83805de4ea1/servicecatalog_puppet/template_builder/hub/bootstrap.py#L1008

https://github.com/awslabs/aws-service-catalog-puppet/blob/288cf1cb9a4620f704cb2e3ded2cb83805de4ea1/servicecatalog_puppet/template_builder/hub/bootstrap.py#L1058

https://github.com/awslabs/aws-service-catalog-puppet/blob/288cf1cb9a4620f704cb2e3ded2cb83805de4ea1/servicecatalog_puppet/constants.py#L215

https://github.com/awslabs/aws-service-catalog-puppet/blob/a1e2b7a37fd866783a530812823bc0cc99406f0d/tests/continuous-runner/serverless.yml#L50

https://github.com/awslabs/aws-service-catalog-puppet/blob/1fb38e1ae78da9f9990d21f5fca0612f23c69c32/servicecatalog_puppet/servicecatalog-puppet-initialiser.template.yaml#L303

Many thanks!

**Comment by eamonnfaherty** [comment]
Hey, thanks for raising the issue.  I have released https://github.com/awslabs/aws-service-catalog-puppet/releases/tag/0.223.0 using image 5 and there is a new initialiser template for the install process.  I have updated the version in the spoke bootstrap template but you do not need to rebootstrap spokes - this is handled for you.

You should be able to upgrade using the docs as normal: https://service-catalog-tools-workshop.com/upgrading/service-catalog-puppet.html

**Comment by peteawood** [comment]
Many thanks for the incredibly quick work @eamonnfaherty!
