### ISSUE TITLE
Puppet product deployment failed for 1st time, but works next time

### ISSUE THREAD

**Issue by babu-selvam** [awslabs/aws-service-catalog-puppet#651]
**Describe the bug**
Puppet is failing to deploy product inthe first run. But 2nd run will deploy the products as per the manifest. 
Puppet failes with following error - "ERROR MainProcess worker#5 botocore.errorfactory.InvalidParametersException: An error occurred (InvalidParametersException) when calling the AssociateProductWithPortfolio operation: Portfolio port-lns4hg532h4k4 must be accepted before you can associate Products from it"

**To Reproduce**
1. Install puppet 0.227.0 version
2. Add a product launch configuration
3. Run puppet pipeline

**Expected behavior**
Puppet should have deployed the product as per manifest. But it is not doing so in the 1st run. But success in the next run.
**Attachments**
Please attach a copy of your manifest, expanded-manifest, logs and build artefacts where appropriate.
[Artifacts.zip](https://github.com/awslabs/aws-service-catalog-puppet/files/11275562/Artifacts.zip)

**Comment by babu-selvam** [comment]
Issue fixed after bootstraping account with new version

**Comment by eamonnfaherty** [comment]
was this an accidental reopen or did you see an issue?

**Comment by babu-selvam** [comment]
Thanks for checking, Issue seems not gone. Still exists for imported-portfolios. Launches are not affected. 

So if any new imported-portfolio is added, I still see this issue. Hence re-opened the case. 

2nd run of puppet solves the issue even now.

**Comment by eamonnfaherty** [comment]
0.227.0 and earlier had an issue with dependencies.  It would be worth trying 0.228.0.
