### ISSUE TITLE
Tooling account Puppet-deploy-in-spoke stuck running "portfolio-get-all-products-and-their-version" against all products.

### ISSUE THREAD

**Issue by myshauno** [awslabs/aws-service-catalog-puppet#664]
**Describe the bug**
After updating to 0.231.0 from 0.171.0 we are experiencing an issue with the **servicecatalog-puppet-deploy-in-spoke** codebuild project running **portfolio-get-all-products-and-their-version** against each account for each individual product in each portfolio it seems.

This is only effecting the **servicecatalog-puppet-deploy-in-spoke** codebuild project within the tooling account.

Example of an entry below:
```
INFO MainProcess scheduler sending: portfolio-get-all-products-and-their-versions-ACCOUNTID-launches-vpc-flow-logs-MFI-cicd--eu-central-1-shared-guardrails
INFO MainProcess worker#2 executing task: portfolio-get-all-products-and-their-versions-ACCOUNTID-launches-vpc-flow-logs-rock-cicd--eu-central-1-shared-guardrails
INFO MainProcess worker#2 GetAllProductsAndTheirVersionsTask:portfolio-get-all-products-and-their-versions-ACCOUNTID-launches-vpc-flow-logs-rock-cicd--eu-central-1-shared-guardrails started
INFO MainProcess worker#2 executed task [success]: portfolio-get-all-products-and-their-versions-ACCOUNTID-launches-vpc-flow-logs-rock-cicd--eu-central-1-shared-guardrails got lock to unlock resources
INFO MainProcess scheduler receiving: [300]: portfolio-get-all-products-and-their-versions-ACCOUNTID-launches-vpc-flow-logs-rock-cicd--eu-central-1-shared-guardrails, COMPLETED
```

I assume this may have to do with the current structure of our puppet repo, as I've been resolving a few issues, we had to remove our spoke-local-portfolios folder just to get the run working initially.

**To Reproduce**
1. Conduct update on **puppet-initialization-stack**, setting the version parameter to: aws-service-catalog-puppet==0.231.0
2. Await successful update notification in CloudFormation stack
2. Go to CodePipeline to run **servicecatalog-puppet-pipeline**

**Expected behavior**
Hoping for a successful run which doesn't hit the codebuild timeout.

**Attachments**
Please let me know what files might assist with diagnosis, I can provide our manifest/insight into our code if/when required.

**Comment by eamonnfaherty** [comment]
Could you please share your manifest files and your full logs.
