### ISSUE TITLE
servicecatalog-puppet-bootstrap-spokes-in-ou Code buold job is failing with attribute Error 

### ISSUE THREAD

**Issue by Palla246** [awslabs/aws-service-catalog-puppet#674]
**Describe the bug**
After updating the puppet version 0.237.0 we are facing issue with "servicecatalog-puppet-bootstrap-spokes-in-ou" code build job. when we provision the new AWS account in our Landing the the above codebuild job is failing with attribute error.

Error Log:
========

ERROR: [pid 320] Worker Worker(salt=7071947843, workers=10, host=5145b5dc992a, username=root, pid=271) failed    BootstrapSpokeAsTask(puppet_account_id=, account_id=, iam_role_arns=["arn:aws:iam::Account ID:role/aac-servicecatalog-puppet-bootstrap-role"], role_name=AWSCloudFormationStackSetExecutionRole, permission_boundary=arn:aws:iam::aws:policy/AdministratorAccess, puppet_role_name=PuppetRole, puppet_role_path=/servicecatalog-puppet/, tag=[])
--
215 | Traceback (most recent call last):
216 | File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/luigi/worker.py", line 198, in run
217 | new_deps = self._run_get_new_deps()
218 | File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
219 | task_gen = self.task.run()
220 | File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/servicecatalog_puppet/workflow/management.py", line 40, in run
221 | self.write_output(self.params_for_results_display())
222 | AttributeError: 'BootstrapSpokeAsTask' object has no attribute 'write_output'
223 | ERROR:luigi-interface:[pid 320] Worker Worker(salt=7071947843, workers=10, host=5145b5dc992a, username=root, pid=271) failed    BootstrapSpokeAsTask(puppet_account_id=, account_id=, iam_role_arns=["arn:aws:iam:::role/aac-servicecatalog-puppet-bootstrap-role"], role_name=AWSCloudFormationStackSetExecutionRole, permission_boundary=arn:aws:iam::aws:policy/AdministratorAccess, puppet_role_name=PuppetRole, puppet_role_path=/servicecatalog-puppet/, tag=[])
224 | Traceback (most recent call last):
225 | File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/luigi/worker.py", line 198, in run
226 | new_deps = self._run_get_new_deps()
227 | File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/luigi/worker.py", line 138, in _run_get_new_deps
228 | task_gen = self.task.run()
229 | File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/servicecatalog_puppet/workflow/management.py", line 40, in run
230 | self.write_output(self.params_for_results_display())
231 | AttributeError: 'BootstrapSpokeAsTask' object has no attribute 'write_output'
232 | INFO: Informed scheduler that task   BootstrapSpokeAsTask_511080193506___arn_aws_iam__2_arn_aws_iam__aws_fe356cfd66   has status   FAILED
233 | INFO:luigi-interface:Informed scheduler that task   BootstrapSpokeAsTask_511080193506___arn_aws_iam__2_arn_aws_iam__aws_fe356cfd66   has status   FAILED
234 | INFO: Worker Worker(salt=7071947843, workers=10, host=5145b5dc992a, username=root, pid=271) was stopped. Shutting down Keep-Alive thread
235 | INFO:luigi-interface:Worker Worker(salt=7071947843, workers=10, host=5145b5dc992a, username=root, pid=271) was stopped. Shutting down Keep-Alive thread
236 | INFO:
237 | ===== Luigi Execution Summary =====
238 |  
239 | Scheduled 1 tasks of which:
240 | * 1 failed:
241 | - 1 BootstrapSpokeAsTask(...)
242 |  
243 | This progress looks :( because there were failed tasks
244 |  
245 | ===== Luigi Execution Summary =====
246 |  
247 | INFO:luigi-interface:
248 | ===== Luigi Execution Summary =====
249 |  
250 | Scheduled 1 tasks of which:
251 | * 1 failed:
252 | - 1 BootstrapSpokeAsTask(...)
253 |  
254 | This progress looks :( because there were failed tasks
255 |  
256 | ===== Luigi Execution Summary =====
257 |  
258 |  
259 | [Container] 2023/07/23 10:06:45 Command did not exit successfully servicecatalog-puppet bootstrap-spokes-in-ou $OU_OR_PATH $IAM_ROLE_NAME $IAM_ROLE_ARNS ${OPTIONS} exit status 1

**To Reproduce**
1. Go to '...'  : Provision New account creation in the landing Zone
2. the service catalog puppet will trigger the "servicecatalog-puppet-bootstrap-spokes-in-ou" job 
3. the above job failed with the error 
   229 | File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/servicecatalog_puppet/workflow/management.py", line 40, in run
230 | self.write_output(self.params_for_results_display())
231 | AttributeError: 'BootstrapSpokeAsTask' object has no attribute 'write_output'

**Expected behavior**
the code build job should get succeded

**Attachments**
Please attach a copy of your manifest, expanded-manifest, logs and build artefacts where appropriate.
I have attached the codebuild job logs for your reference
[log-events-viewer-result.csv](https://github.com/awslabs/aws-service-catalog-puppet/files/12144797/log-events-viewer-result.csv)

**Comment by eamonnfaherty** [comment]
resolved in https://github.com/awslabs/aws-service-catalog-puppet/releases/tag/0.238.0
