### ISSUE TITLE
PyYAML dependency breaks installation

### ISSUE THREAD

**Issue by ruvimrd** [awslabs/aws-service-catalog-puppet#683]
**Describe the bug**
PyYAML v5.4 is broken as seen [here](https://github.com/yaml/pyyaml/issues/724) when used with cython 3.
This causes the overall package installation to fail.

Can the setup.py be updated to use pyyaml==6.0.1 which fixes the error?

**To Reproduce**
Run 'pip install aws-service-catalog-puppet'

**Expected behavior**

**Attachments**

**Comment by eamonnfaherty** [comment]
Resolved in https://github.com/awslabs/aws-service-catalog-puppet/releases/tag/0.241.0

**Comment by ruvimrd** [comment]
Thanks for updating the version @eamonnfaherty.
A few others and I were experiencing this issue with python 9.

The recent release of Cython 3 broke a few packages similar to this, and pyyaml v6.0.1 pinned the build dependency to Cython>3.0 to avoid this issue.

**Comment by eamonnfaherty** [comment]
Some point soon I am going to reduce the dependencies of the project to reduce the risk of these issues.  PyYAML will probably remain in but others like colorclass could probably be dropped with little end user impact. 

Thanks for your patience on this issue.
