### ISSUE TITLE
Change Lambda runtime from python3.7 to python3.9

### ISSUE THREAD

**Issue by mpratsch** [awslabs/aws-service-catalog-puppet#695]
**Is your feature request related to a problem? Please describe.**

That's not a problem yet but the support of the Lambda runtime **python3.7 ends soon**.
It seems there is just one left over in the intialiser template:
https://github.com/awslabs/aws-service-catalog-puppet/blob/149313c673327aa56f40cf6ecbaece4aa553562c/servicecatalog_puppet/servicecatalog-puppet-initialiser.template.yaml#L474

The same also goes for the factory initialiser template:
https://github.com/awslabs/aws-service-catalog-factory/blob/a64baa0fc36e8d957705f1db0d1ca5ba29a30586/servicecatalog_factory/servicecatalog-factory-initialiser.template.yaml#L285

Can you please change and test that, Eamonn?

Thanks and all the best, 
Martina

**Comment by eamonnfaherty** [comment]
released in https://github.com/awslabs/aws-service-catalog-puppet/releases/tag/0.245.0
