### ISSUE TITLE
ThrottlingException in CopyIntoSpokeLocalPortfolioTask for UpdateProvisioningArtifact operation After upgrade from 0.158.1 to 0.245.0 

### ISSUE THREAD

**Issue by naspinec** [awslabs/aws-service-catalog-puppet#702]
**Describe the bug**
After upgrade we have multiple errors reported to OpsCenter :
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-productionDSI-351396677331-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-productionDSI-456887537389-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-productionDSI-408778737270-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-productionDCO-83575**95684-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-productionDCO-130252104593-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-productionDCO-575222302896-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-productionDCO-132712841556-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-productionSIMBA-65719579**00-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-productionDSI-906407651430-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-productionDCO-236209914455-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-productionDCO-625253021259-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-productionDCO-410044523193-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-hors-productionSIMBA-994790662519-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-productionDCO-861882705642-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-productionDSI-903438043401-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-productionDCO-800664649472-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-productionDCO-235549676132-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-productionDCO-098989725794-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-productionDSI-474594327943-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-hors-productionDSI-580097817195-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-productionDCO-900868242524-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-productionDCO-06341140**90-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-hors-productionDCO-852715837224-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-productionDCO-981481652025-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-hors-productionDSI-171421041177-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-hors-productionDCO-855302029544-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-productionDCO-721130081523-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-hors-productionDSI-659281631275-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-hors-productionDSI-481372**5186-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-hors-productionDSI-679173822591-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-hors-productionDCO-875238464494-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-productionDCO-870665672198-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-hors-productionDCO-941613920020-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-hors-productionDSI-174**4589376-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-hors-productionDCO-918867391411-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-hors-productionDCO-972102809228-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-hors-productionDCO-177869251340-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-hors-productionDCO-637586022430-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-hors-productionDCO-331556910160-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-hors-productionDCO-556331131039-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-experimentationDSI-513152608812-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-experimentationDSI-010215673994-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-experimentationDSI-910428278628-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-hors-productionDCO-427846637394-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-hors-productionDCO-441956901130-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-experimentationDSI-17**54599381-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-experimentationDSI-226643154437-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-hors-productionDCO-039928249126-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-experimentationDSI-548314051349-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-hors-productionDSI-429**5986900-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-hors-productionDCO-026077384863-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-experimentationDSI-935588196488-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-experimentationDSI-582528916400-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-hors-productionDCO-082073012515-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-devops-304940787246-eu-west-1-sc-devops-devops-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-experimentationDSI-170940864353-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-experimentationDSI-240556064472-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-experimentationDSI-372072030207-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-experimentationDSI-553426436829-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-experimentationDSI-951258348078-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-devops-**8465799202-eu-west-1-sc-devops-devops-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-hors-productionDCO-535481890514-eu-west-1-sc-ccoe-shared-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-devops-04082678**77-eu-west-1-sc-devops-devops-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-devops-093476979193-eu-west-1-sc-devops-devops-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-devops-928407843622-eu-west-1-sc-devops-devops-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-devops-344200352564-eu-west-1-sc-devops-devops-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CopyIntoSpokeLocalPortfolioTask failed: portfolio_copy-spoke-local-portfolios-account-vending-for-devops-490957187238-eu-west-1-sc-devops-devops-portfolio
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None
INFO MainProcess MainThread Sending failure to opscenter: CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask failed: None

**To Reproduce**

**Expected behavior**
We don't know what causes these errors as the manifest didn't change between the old and the new version.

**Attachments**
[rdG6HRK.zip](https://github.com/awslabs/aws-service-catalog-puppet/files/13922499/rdG6HRK.zip)
Please attach a copy of your manifest, expanded-manifest, logs and build artefacts where appropriate.

**Comment by eamonnfaherty** [comment]
Following a call this issue was diagnosed as :

CopyIntoSpokeLocalPortfolioTask raises a throttling error for UpdateProvisioningArtifact in certain scenarios.
