### ISSUE TITLE
Launch constrains are not applied after update to 0.246.0

### ISSUE THREAD

**Issue by naspinec** [awslabs/aws-service-catalog-puppet#705]
**Describe the bug**
Launch constrains are not applied after update to 0.246.0

**To Reproduce**

**Expected behavior**
Have launch constrains applied to products associated to portfolios.

**Attachments**
Please attach a copy of your manifest, expanded-manifest, logs and build artefacts where appropriate.
[manifest.yaml.txt](https://github.com/awslabs/aws-service-catalog-puppet/files/14378664/manifest.yaml.txt)
[manifest-expanded.yaml.txt](https://github.com/awslabs/aws-service-catalog-puppet/files/14378665/manifest-expanded.yaml.txt)
[CreateAssociationsForSpokeLocalPortfolioTask-CreateAssociationsForSpokeLocalPortfolioTask_515411312103___arn_aws_iam______spoke_local_po_317fd571b4.json.txt](https://github.com/awslabs/aws-service-catalog-puppet/files/14378672/CreateAssociationsForSpokeLocalPortfolioTask-CreateAssociationsForSpokeLocalPortfolioTask_515411312103___arn_aws_iam______spoke_local_po_317fd571b4.json.txt)
[CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask-CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask_006805366288___spoke_local_po____products______81075ad8e1.json.txt](https://github.com/awslabs/aws-service-catalog-puppet/files/14378677/CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask-CreateLaunchRoleConstraintsForSpokeLocalPortfolioTask_006805366288___spoke_local_po____products______81075ad8e1.json.txt)
[puppet-run-logs.zip](https://github.com/awslabs/aws-service-catalog-puppet/files/14378682/puppet-run-logs.zip)

**Comment by eamonnfaherty** [comment]
the current version assumes each portfolio will only be shared once via a single spoke-local-portfolio

This is not aligned to how the solution is being used.
