### ISSUE TITLE
Share local portfolio to cross region is not working, showing ProductId parameter is missing

### ISSUE THREAD

**Issue by vasindran** [awslabs/aws-service-catalog-puppet#722]
**Describe the bug**
While running puppet to share local portfolio to another region, its got error and show some error

**To Reproduce**
1. Go to manifest file for the share local portfolio
2. Add the region (which is enabled already) to share the local portfolio
3. Run the puppet pipeline
4. Puppet codebuild is failed and showing below error.

`INFO MainProcess worker#8 CopyIntoSpokeLocalPortfolioTask:portfolio_copy-spoke-local-portfolios-developers-portfolio-for-spokes-XXXXX-eu-central-1-developers-portfolio started
INFO MainProcess worker#8 portfolio_copy-spoke-local-portfolios-developers-portfolio-for-spokes-XXXXX-eu-central-1-developers-portfolio: Finished copying products
INFO MainProcess worker#7 portfolio_copy-spoke-local-portfolios-developers-portfolio-for-spokes-XXXXX-us-east-2-developers-portfolio: Finished copying products
INFO MainProcess worker#8 portfolio_copy-spoke-local-portfolios-developers-portfolio-for-spokes-XXXXX-eu-central-1-developers-portfolio: Finished waiting for copy products
INFO MainProcess worker#7 portfolio_copy-spoke-local-portfolios-developers-portfolio-for-spokes-XXXXX-us-east-2-developers-portfolio: Finished waiting for copy products
ERROR MainProcess worker#7 executed task [failure]: portfolio_copy-spoke-local-portfolios-developers-portfolio-for-spokes-**XXXXX-us-east-2-developers-portfolio failures: Parameter validation failed:
Invalid type for parameter ProductId, value: True, type: <class 'bool'>, valid types: <class 'str'>**
ERROR MainProcess worker#7 ---- START OF ERROR----
ERROR MainProcess worker#7 Task CopyIntoSpokeLocalPortfolioTask:
ERROR MainProcess worker#7 account_id: 'XXXXX'
ERROR MainProcess worker#7 dependencies_by_reference:
ERROR MainProcess worker#7 - spoke-local-portfolios_developers-portfolio-for-spokes_XXXXX_us_east_2
ERROR MainProcess worker#7 - portfolio-get-all-products-and-their-versions-XXXXX-us-east-2-developers-portfolio
ERROR MainProcess worker#7 - portfolio-get-all-products-and-their-versions-before-911682453555-us-east-2-developers-portfolio
ERROR MainProcess worker#7 manifest_files_path: .
ERROR MainProcess worker#7 manifest_task_reference_file_path: ./manifest-task-reference.json
ERROR MainProcess worker#7 portfolio_get_all_products_and_their_versions_for_hub_ref: portfolio-get-all-products-and-their-versions-before-911682453555-us-east-2-developers-portfolio
ERROR MainProcess worker#7 portfolio_get_all_products_and_their_versions_ref: portfolio-get-all-products-and-their-versions-XXXXX-us-east-2-developers-portfolio
ERROR MainProcess worker#7 portfolio_task_reference: spoke-local-portfolios_developers-portfolio-for-spokes_XXXXX_us_east_2
ERROR MainProcess worker#7 puppet_account_id: '911682453555'
ERROR MainProcess worker#7 region: us-east-2
ERROR MainProcess worker#7 task_reference: portfolio_copy-spoke-local-portfolios-developers-portfolio-for-spokes-XXXXX-us-east-2-developers-portfolio
ERROR MainProcess worker#7 
ERROR MainProcess worker#7 Traceback (most recent call last):
ERROR MainProcess worker#7 
ERROR MainProcess worker#7   File "/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/servicecatalog_puppet/waluigi/shared_tasks/workers/worker_requiring_scheduler.py", line 100, in worker_task
ERROR MainProcess worker#7     task.execute()
ERROR MainProcess worker#7 
ERROR MainProcess worker#7   File "/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/servicecatalog_puppet/waluigi/task_mixins/task_executor_mixin.py", line 35, in execute
ERROR MainProcess worker#7     self.run()
ERROR MainProcess worker#7 
ERROR MainProcess worker#7   File "/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/servicecatalog_puppet/workflow/portfolio/portfolio_management/copy_into_spoke_local_portfolio_task.py", line 127, in run
ERROR MainProcess worker#7     servicecatalog.associate_product_with_portfolio(
ERROR MainProcess worker#7 
ERROR MainProcess worker#7   File "/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/botocore/client.py", line 5**, in _api_call
ERROR MainProcess worker#7     return self._make_api_call(operation_name, kwargs)
ERROR MainProcess worker#7 
ERROR MainProcess worker#7   File "/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/botocore/client.py", line 919, in _make_api_call
ERROR MainProcess worker#7     request_dict = self._convert_to_request_dict(
ERROR MainProcess worker#7 
ERROR MainProcess worker#7   File "/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/botocore/client.py", line 990, in _convert_to_request_dict
ERROR MainProcess worker#7     request_dict = self._serializer.serialize_to_request(
ERROR MainProcess worker#7 
ERROR MainProcess worker#7   File "/root/.pyenv/versions/3.9.17/lib/python3.9/site-packages/botocore/validate.py", line 381, in serialize_to_request
ERROR MainProcess worker#7     raise ParamValidationError(report=report.generate_report())
ERROR MainProcess worker#7 
ERROR MainProcess worker#7 botocore.exceptions.ParamValidationError: Parameter validation failed:
ERROR MainProcess worker#7 Invalid type for parameter ProductId, value: True, type: <class 'bool'>, valid types: <class 'str'>
ERROR MainProcess worker#7 
ERROR MainProcess worker#7 ---- END OF ERROR ----
INFO MainProcess worker#7 executed task [success]: portfolio_copy-spoke-local-portfolios-developers-portfolio-for-spokes-XXXXX-us-east-2-developers-portfolio got lock to unlock resources
INFO MainProcess scheduler receiving: [1]: portfolio_copy-spoke-local-portfolios-developers-portfolio-for-spokes-XXXXX-us-east-2-developers-portfolio, ERRORED
INFO MainProcess scheduler tasks now scheduled
INFO MainProcess worker#8 portfolio_copy-spoke-local-portfolios-developers-portfolio-for-spokes-XXXXX-eu-central-1-developers-portfolio: Finished associating products
INFO MainProcess worker#8 portfolio_copy-spoke-local-portfolios-developers-portfolio-for-spokes-XXXXX-eu-central-1-developers-portfolio: Finished updating versions that were copied
INFO MainProcess worker#8 portfolio_copy-spoke-local-portfolios-developers-portfolio-for-spokes-XXXXX-eu-central-1-developers-portfolio: Finished waiting for association of products to portfolio
INFO MainProcess worker#8 executed task [success]: portfolio_copy-spoke-local-portfolios-developers-portfolio-for-spokes-XXXXX-eu-central-1-developers-portfolio got lock to unlock resources`

**Expected behavior**
The local portfolio should be shared across the region

**Attachments**
Version of puppet is install ***-service-catalog-puppet==0.246.0

**Comment by eamonnfaherty** [comment]
I hope to have a fix for portfolio not sharing this week.

**Comment by vasindran** [comment]
Thanks Eamonn, awaiting for your fix.

**Comment by eamonnfaherty** [comment]
I am unable to reproduce your issue. Are there products in the source portfolio that is being shared? There needs to be at least product in the portfolio for it to be sharable. If you have at least one product in the portfolio then reopen this and let me know the names of the products in the portfolio being shared.
