### ISSUE TITLE
Unable to terminate launch in v0.1.14

### ISSUE THREAD

**Issue by HieronymusLex** [awslabs/aws-service-catalog-puppet#73]
After upgrading to 0.1.14, setting the status of a launch to terminated is causing an exception (`luigi.parameter.UnknownParameterException: TerminateProductTask[...]: unknown parameter worker_timeout`) to be raised during the deploy state of the puppet pipeline (causing the pipeline to fail). 

The error is raised during execution of `servicecatalog-puppet --info deploy manifest-expanded.yaml`

The `worker_timeout` parameter added in #68 to `deploy_launches_task_builder_for_account_launch_region` is missing from `TerminateProductTask`

**Comment by eamonnfaherty** [comment]
thanks for reporting this.  a fix is on its way.

**Comment by eamonnfaherty** [comment]
created this: https://github.com/awslabs/aws-service-catalog-puppet/issues/76

**Comment by eamonnfaherty** [comment]
Closing this
