### ISSUE TITLE
Local Portfolio Setup - Imported Version Launched

### ISSUE THREAD

**Issue by jordan-evans** [awslabs/aws-service-catalog-puppet#83]
At the moment I have an account that has a few products deployed to it from the “Imported Portfolio” setup. I now want to switch this over to use the new local portfolio setup (to make use of launch constraints). 

I’ve added in config to switch it over to use the local setup, and this initially worked fine. I was expecting my products needing to be terminated & re-deployed after switching to the local portfolio but they didn’t (which I thought was a little odd, as the underlying product artefact should have changed).

I then tried terminating one of the products, and then asking Puppet to re-deploy it. I expected that Puppet would use the local product this time, but it instead used the imported one. Is this intended? I expected a local one to win over an imported one?

Thanks!

**Comment by eamonnfaherty** [comment]
The imported and the local portfolios are independent of each other.  The solution was not intended to solve the issue of launch constraints for puppet deployed products.  The product was deployed by puppet and so no launch constraints should be needed.

I am pretty sure I understand what you are trying to do but am curious why you would want launch constraints for product that is deployed by a service?

**Comment by jordan-evans** [comment]
Ok, that makes sense. I think I need to refactor my portfolio setup slightly to accommodate this. Will give that a try now, and will re-open this if necessary.

**Comment by eamonnfaherty** [comment]
Great, thanks a million and please do reach out if you get stuck.

**Comment by jordan-evans** [comment]
Sorry, to answer your question!

I want to lock down the ability to do certain actions for arguments sake, lets say creating a VPC, unless its carried out via Service Catalog. 

At the moment I'll be doing this via an SCP. However SCPs also affect Service Catalog, so I want Service Catalog to launch certain products using a role that I have whitelisted from the SCP (via a Condition).

In this case, I won't be using Puppet to deploy the VPC product, end users will be provisioning it, so a refactor of my portfolios should solve the issue. 

However if I wanted Puppet to also deploy that service, would I be able to? It sounds like the answer is "no"? 

Thanks!

**Comment by eamonnfaherty** [comment]
I checked with some of my peers and the response was adding exceptions to the SCP.

Here is an article describing the approach https://aws.amazon.com/blogs/security/how-to-use-service-control-policies-to-set-permission-guardrails-across-accounts-in-your-aws-organization/ search for "Grant an exception to your SCP for an administrator role" to find the section.

When adding exceptions please remember to include the roles used when reacting to an incident.

**Comment by jordan-evans** [comment]
Yes, I'm happy with that, but with a Puppet deployed product what would you whitelist? With a local product I can use a launch constraint to control what role is used to deploy the resources (A role I can exempt from the SCP).

But with a Puppet deployed product I can't do that. Whitelisting the `PuppetRole` wouldn't work as that is only used to call the ProvisionProduct API, it doesn't continue to use that role to deploy resources (at least I'm pretty sure that's the case).

**Comment by eamonnfaherty** [comment]
I have a good understanding of what you are trying to achieve.  I will reach out to make some enquires on the recommended approach and add it to the docs for this project

**Comment by eamonnfaherty** [comment]
I have added https://github.com/awslabs/aws-service-catalog-puppet/issues/85 to track this

**Comment by jordan-evans** [comment]
Thanks. This would be easily solved if imported products could use a role in the target account as a launch constraint (something like `arn:aws:iam::*:role/MyServiceCatalogDeploymentRole`), so the answer might be for the Service Catalog team to implement. But having the use case documented would be good to help other users 😄
